name: How is the average order amount ($) trending each week??
description: How is the average order amount ($) trending each week?
tableName: dbt_orders
updatedAt: "2026-01-13T18:26:15.909Z"
metricQuery:
  exploreName: dbt_orders
  dimensions:
    - dbt_orders_order_date_week
  metrics:
    - dbt_orders_average_of_basket_total
  filters: {}
  sorts:
    - fieldId: dbt_orders_order_date_week
      descending: true
  limit: 500
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: cartesian
  config:
    layout:
      stack: stack
      xField: dbt_orders_order_date_week
      yField:
        - dbt_orders_average_of_basket_total
      flipAxes: false
      showGridY: false
      showYAxis: false
    eChartsConfig:
      grid:
        top: 5px
        left: 25px
        right: 5px
        bottom: 30px
        containLabel: true
      xAxis:
        - name: Week
          rotate: 30
      yAxis:
        - max: "200"
          min: "50"
          name: Average order amount ($)
        - {}
      series:
        - type: line
          label:
            show: true
            position: top
          stack: stack-all-series
          encode:
            xRef:
              field: dbt_orders_order_date_week
            yRef:
              field: dbt_orders_average_of_basket_total
          areaStyle: {}
          yAxisIndex: 0
          isFilteredOut: false
      tooltip: ""
      showAxisTicks: false
slug: how-is-the-average-order-amount-trending-each-week-
tableConfig:
  columnOrder:
    - dbt_orders_order_date_week
    - dbt_orders_average_of_basket_total
spaceSlug: shared
version: 1
downloadedAt: "2026-02-24T19:01:19.448Z"
