name: How much profit do we receive per month per partner?
description: "How much revenue did each sales partner bring in each month? "
tableName: dbt_orders
updatedAt: "2026-02-03T11:21:12.293Z"
metricQuery:
  exploreName: dbt_orders
  dimensions:
    - dbt_orders_partner_name
    - dbt_orders_order_date_month
  metrics:
    - dbt_orders_sum_of_profit
  filters: {}
  sorts:
    - fieldId: dbt_orders_order_date_month
      descending: true
  limit: 500
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics:
    - name: user_id_count_distinct
      label: Count distinct of User id
      description: >-
        Count distinct of User id on the table Dbt orders. Lightdash has created
        this metric automatically.
      uuid: 03d88713-ac77-4c06-9f4e-dd9783e69fc9
      sql: ${TABLE}.user_id
      table: dbt_orders
      type: count_distinct
    - name: order_id_count_distinct
      label: Count distinct of Order id
      description: >-
        Count distinct of Order id on the table Dbt orders. Lightdash has
        created this metric automatically.
      uuid: 2b1a6951-ca37-48b2-818c-76ab6a915e3d
      sql: ${TABLE}.order_id
      table: dbt_orders
      type: count_distinct
    - name: partner_id_count_distinct
      label: Count distinct of Partner id
      description: >-
        Count distinct of Partner id on the table Dbt orders. Lightdash has
        created this metric automatically.
      uuid: f7c8e535-f6c0-46d1-acf7-f1719198d732
      sql: ${TABLE}.partner_id
      table: dbt_orders
      type: count_distinct
    - name: profit_sum_sum_of_profit_xxx_total_profit
      label: Total Profit
      description: "Sum of Sum of Profit xxx on the table Orders "
      uuid: 1f3c52f9-25fc-402d-a2a7-ad901013f5ab
      sql: ${TABLE}.profit
      table: dbt_orders
      type: sum
  customDimensions: []
chartConfig:
  type: table
  config:
    columns:
      dbt_orders_partner_name:
        name: ""
      dbt_orders_sum_of_profit:
        name: ""
      dbt_orders_order_date_month:
        name: ""
    metricsAsRows: false
    showSubtotals: false
    hideRowNumbers: false
    showTableNames: false
    showResultsTotal: false
    showRowCalculation: false
    showColumnCalculation: false
    conditionalFormattings:
      - color: "#D4E8D4"
        rules:
          - id: rule-1
            values:
              - 50000
            operator: greaterThan
        target:
          fieldId: dbt_orders_sum_of_profit
      - color: "#B8D4B8"
        rules:
          - id: rule-2
            values:
              - 100000
            operator: greaterThan
        target:
          fieldId: dbt_orders_sum_of_profit
      - color: "#9CC09C"
        rules:
          - id: rule-3
            values:
              - 150000
            operator: greaterThan
        target:
          fieldId: dbt_orders_sum_of_profit
      - color: "#80AC80"
        rules:
          - id: rule-4
            values:
              - 200000
            operator: greaterThan
        target:
          fieldId: dbt_orders_sum_of_profit
      - color: "#649864"
        rules:
          - id: rule-5
            values:
              - 250000
            operator: greaterThan
        target:
          fieldId: dbt_orders_sum_of_profit
slug: how-much-profit-do-we-receive-per-month-per-partner-
tableConfig:
  columnOrder:
    - dbt_orders_partner_name
    - dbt_orders_order_date_month
    - dbt_orders_sum_of_profit
spaceSlug: "-sales"
version: 1
downloadedAt: "2026-03-09T14:59:04.061Z"
