name: How many orders have we fulfilled??
description: null
tableName: dbt_orders
updatedAt: "2026-03-05T12:25:55.211Z"
metricQuery:
  exploreName: dbt_orders
  dimensions:
    - dbt_orders_order_date_month
  metrics:
    - dbt_orders_count_distinct_order_id
    - dbt_orders_average_of_basket_total
  filters: {}
  sorts:
    - fieldId: dbt_orders_count_distinct_order_id
      descending: true
  limit: 500
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: big_number
  config:
    label: Orders fulfilled
    flipColors: false
    selectedField: dbt_orders_count_distinct_order_id
    showComparison: true
    comparisonLabel: MoM
    comparisonFormat: percentage
    showBigNumberLabel: true
    showTableNamesInLabel: true
slug: how-many-orders-have-we-fulfilled-
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_count_distinct_order_id
    - dbt_orders_average_of_basket_total
spaceSlug: "-sales"
version: 1
downloadedAt: "2026-03-09T14:57:46.755Z"
