name: Orders per Partner
description: ""
tableName: dbt_orders
updatedAt: "2026-03-05T12:25:55.215Z"
metricQuery:
  exploreName: dbt_orders
  dimensions:
    - dbt_orders_partner_name
  metrics:
    - dbt_orders_count_distinct_order_id
  filters: {}
  sorts:
    - fieldId: dbt_orders_count_distinct_order_id
      descending: true
  limit: 500
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: cartesian
  config:
    layout:
      stack: none
      xField: dbt_orders_partner_name
      yField:
        - dbt_orders_count_distinct_order_id
      flipAxes: true
      showGridY: false
      showXAxis: false
      showYAxis: true
    eChartsConfig:
      xAxis:
        - name: " "
          rotate: 60
          inverse: false
          sortType: bar_totals
      yAxis:
        - name: Order count
        - {}
      series:
        - type: bar
          label:
            show: true
            position: right
          encode:
            xRef:
              field: dbt_orders_partner_name
            yRef:
              field: dbt_orders_count_distinct_order_id
          yAxisIndex: 0
          isFilteredOut: false
      tooltip: ""
dashboardSlug: "-kpi-dashboard"
slug: orders-per-partner
tableConfig:
  columnOrder:
    - dbt_orders_partner_name
    - dbt_orders_count_distinct_order_id
spaceSlug: "-key-company-dashboards"
version: 1
downloadedAt: "2026-03-09T14:57:46.755Z"
