name: Partner profit performance (not affected by Partner dashboard filter)
description: ""
tableName: dbt_baskets
updatedAt: "2025-12-09T22:40:58.800Z"
metricQuery:
  exploreName: dbt_baskets
  dimensions:
    - dbt_baskets_partner_name
  metrics:
    - dbt_baskets_sum_of_basket_total
    - dbt_baskets_sum_of_item_profit
    - dbt_baskets_average_of_item_profit
  filters: {}
  sorts:
    - fieldId: dbt_baskets_sum_of_item_profit
      descending: true
  limit: 500
  metricOverrides: {}
  tableCalculations:
    - name: profit_margin_1
      displayName: Profit margin
      sql: ${dbt_baskets.sum_of_item_profit}/${dbt_baskets.sum_of_basket_total}
      format:
        type: percent
        round: 1
        currency: USD
        separator: default
      type: number
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: table
  config:
    columns:
      dbt_baskets_sum_of_item_profit:
        displayStyle: text
      dbt_baskets_sum_of_basket_total:
        displayStyle: text
      dbt_baskets_average_of_item_profit:
        color: "#8b8cf6"
        displayStyle: bar
    metricsAsRows: false
    showSubtotals: false
    hideRowNumbers: true
    showTableNames: false
    showResultsTotal: false
    showRowCalculation: false
    showColumnCalculation: true
    conditionalFormattings:
      - rule:
          max: auto
          min: auto
        color:
          end: "#8b8cf6"
          start: "#ffffff"
        target:
          fieldId: dbt_baskets_sum_of_item_profit
      - rule:
          max: auto
          min: auto
        color:
          end: "#8b8cf6"
          start: "#ffffff"
        target:
          fieldId: dbt_baskets_sum_of_basket_total
dashboardSlug: "-kpi-dashboard"
slug: partner-profit-performance
tableConfig:
  columnOrder:
    - dbt_baskets_partner_name
    - dbt_baskets_sum_of_basket_total
    - dbt_baskets_sum_of_item_profit
    - dbt_baskets_average_of_item_profit
    - profit_margin_1
spaceSlug: "-key-company-dashboards"
version: 1
downloadedAt: "2026-02-24T19:01:19.448Z"
