name: Revenue by Partner (Last 6 Completed Months)
description: Total revenue by partner, filtered to the last 6 completed months.
tableName: dbt_orders
updatedAt: "2026-02-24T19:15:00.000Z"
metricQuery:
  exploreName: dbt_orders
  dimensions:
    - dbt_orders_partner_name
  metrics:
    - dbt_orders_sum_of_basket_total
  filters:
    dimensions:
      id: c2453bc8-a960-45fa-9dbd-dd6317dd18ba
      and:
        - id: f5232c22-ace9-4383-97ad-6de6d79ae852
          target:
            fieldId: dbt_orders_order_date_day
            fieldFilterType: date
          values:
            - 6
          operator: inThePast
          settings:
            completed: true
            unitOfTime: months
  sorts:
    - fieldId: dbt_orders_sum_of_basket_total
      descending: true
  limit: 50
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: cartesian
  config:
    layout:
      xField: dbt_orders_partner_name
      yField:
        - dbt_orders_sum_of_basket_total
      flipAxes: true
    eChartsConfig:
      grid:
        containLabel: true
      xAxis:
        - name: Partner
      yAxis:
        - name: Total revenue
      legend:
        show: true
        type: scroll
      series:
        - name: Total Revenue
          type: bar
          encode:
            xRef:
              field: dbt_orders_partner_name
            yRef:
              field: dbt_orders_sum_of_basket_total
          yAxisIndex: 0
          isFilteredOut: false
      showAxisTicks: false
dashboardSlug: "-kpi-dashboard"
slug: revenue-by-partner-last-6-completed-months
tableConfig:
  columnOrder:
    - dbt_orders_partner_name
    - dbt_orders_sum_of_basket_total
spaceSlug: "-key-company-dashboards"
version: 1
downloadedAt: "2026-02-24T19:01:19.448Z"
