name: Top 5 products by revenue
description: Ranks products by total Revenue and returns the top 5 products.
tableName: dbt_baskets
updatedAt: "2026-03-05T12:25:55.215Z"
metricQuery:
  exploreName: dbt_baskets
  dimensions:
    - dbt_baskets_product_name
  metrics:
    - dbt_baskets_sum_of_basket_total
  filters:
    metrics:
      id: 30aac9b6-b74b-4c2a-8dde-cd8df08d8edd
      and: []
    dimensions:
      id: 0a8c2e7e-42df-4d29-aabe-2b5169258ead
      and: []
    tableCalculations:
      id: 76426274-ba88-47fd-85c2-8578d84a89c0
      and: []
  sorts:
    - fieldId: dbt_baskets_sum_of_basket_total
      descending: true
  limit: 5
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: cartesian
  config:
    layout:
      stack: false
      xField: dbt_baskets_product_name
      yField:
        - dbt_baskets_sum_of_basket_total
    eChartsConfig:
      grid:
        containLabel: true
      title:
        text: Top 5 products by revenue
      xAxis:
        - name: Product
      yAxis:
        - name: Revenue
      legend:
        show: true
        type: scroll
      series:
        - name: Revenue
          type: bar
          encode:
            xRef:
              field: dbt_baskets_product_name
            yRef:
              field: dbt_baskets_sum_of_basket_total
          yAxisIndex: 0
          isFilteredOut: false
      showAxisTicks: false
dashboardSlug: "-kpi-dashboard"
slug: top-5-products-by-revenue-4
tableConfig:
  columnOrder:
    - dbt_baskets_product_name
    - dbt_baskets_sum_of_basket_total
spaceSlug: "-key-company-dashboards"
version: 1
downloadedAt: "2026-03-09T14:57:46.755Z"
