name: What is our total revenue this month?
description: "The total revenue we get every month from all customers "
tableName: dbt_orders
updatedAt: "2026-03-05T12:25:55.211Z"
metricQuery:
  exploreName: dbt_orders
  dimensions:
    - dbt_orders_order_date_month
    - dbt_orders_partner_commission
  metrics:
    - dbt_orders_sum_of_basket_total
    - dbt_orders_sum_of_profit
  filters:
    dimensions:
      id: 7d05215d-1fd7-4bda-8694-d9d3cee4da83
      and:
        - id: fecaec2a-1397-401b-8d36-ad6de29b9b31
          target:
            fieldId: dbt_orders_browser
          values: []
          operator: equals
          required: false
  sorts:
    - fieldId: dbt_orders_sum_of_basket_total
      descending: true
  limit: 500
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: big_number
  config:
    label: Total Revenue
    style: thousands
    flipColors: false
    selectedField: dbt_orders_sum_of_basket_total
    showComparison: true
    comparisonLabel: MoM
    comparisonFormat: raw
    showBigNumberLabel: true
    showTableNamesInLabel: true
    conditionalFormattings:
      - color: "#ff7a6b"
        rules:
          - id: 85420c3b-beef-4a2d-b323-b5f962d41224
            values:
              - 200000
            operator: lessThan
        target: null
        darkColor: "#ffb898"
      - color: "#ffc658"
        rules:
          - id: 574df166-2f56-45ef-a78f-76a9257072ca
            values:
              - 200000
              - 250000
            operator: inBetween
        target: null
        darkColor: "#ffeabd"
      - color: "#7cde96"
        rules:
          - id: ab1744e7-e611-4f1a-9824-60b1c185c3d6
            values:
              - 250000
            operator: greaterThanOrEqual
        target: null
        darkColor: "#b8f5c8"
slug: what-is-our-total-revenue-
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_partner_commission
    - dbt_orders_sum_of_basket_total
    - dbt_orders_sum_of_profit
spaceSlug: "-sales"
version: 1
downloadedAt: "2026-03-09T14:57:46.755Z"
