name: What are the most popular products?
description: the most popular products by count of product name
tableName: dbt_baskets
updatedAt: "2026-02-03T11:25:26.729Z"
metricQuery:
  exploreName: dbt_baskets
  dimensions:
    - dbt_baskets_product_name
  metrics:
    - dbt_baskets_count_of_product_name
  filters: {}
  sorts:
    - fieldId: dbt_baskets_count_of_product_name
      descending: true
  limit: 500
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: cartesian
  config:
    layout:
      xField: dbt_baskets_product_name
      yField:
        - dbt_baskets_count_of_product_name
      flipAxes: true
    eChartsConfig:
      xAxis:
        - name: Product
          type: category
      yAxis:
        - name: Count
      series:
        - type: bar
          color: "#5C7F9D"
          encode:
            xRef:
              field: dbt_baskets_product_name
            yRef:
              field: dbt_baskets_count_of_product_name
slug: what-are-the-most-popular-products-
tableConfig:
  columnOrder:
    - dbt_baskets_product_name
    - dbt_baskets_count_of_product_name
spaceSlug: "-sales"
version: 1
downloadedAt: "2026-03-09T14:59:04.061Z"
