name: What are the most profitable products?
description: null
tableName: dbt_baskets
updatedAt: "2026-02-03T11:25:27.026Z"
metricQuery:
  exploreName: dbt_baskets
  dimensions:
    - dbt_baskets_product_name
    - dbt_baskets_partner_name
  metrics:
    - dbt_baskets_sum_of_item_profit
  filters: {}
  sorts:
    - fieldId: dbt_baskets_sum_of_item_profit
      descending: true
  limit: 500
  metricOverrides: {}
  dimensionOverrides: {}
  tableCalculations: []
  additionalMetrics: []
  customDimensions: []
chartConfig:
  type: table
  config:
    columns:
      dbt_baskets_partner_name:
        name: ""
      dbt_baskets_product_name:
        name: ""
      dbt_baskets_sum_of_item_profit:
        name: ""
    metricsAsRows: false
    showSubtotals: false
    hideRowNumbers: false
    showTableNames: false
    showResultsTotal: false
    showRowCalculation: false
    showColumnCalculation: false
    conditionalFormattings:
      - color: "#D4E8D4"
        rules:
          - id: rule-1
            values:
              - 1000
            operator: greaterThan
        target:
          fieldId: dbt_baskets_sum_of_item_profit
      - color: "#B8D4B8"
        rules:
          - id: rule-2
            values:
              - 5000
            operator: greaterThan
        target:
          fieldId: dbt_baskets_sum_of_item_profit
      - color: "#9CC09C"
        rules:
          - id: rule-3
            values:
              - 10000
            operator: greaterThan
        target:
          fieldId: dbt_baskets_sum_of_item_profit
      - color: "#80AC80"
        rules:
          - id: rule-4
            values:
              - 15000
            operator: greaterThan
        target:
          fieldId: dbt_baskets_sum_of_item_profit
      - color: "#649864"
        rules:
          - id: rule-5
            values:
              - 20000
            operator: greaterThan
        target:
          fieldId: dbt_baskets_sum_of_item_profit
slug: what-are-the-most-profitable-products-
tableConfig:
  columnOrder:
    - dbt_baskets_product_name
    - dbt_baskets_partner_name
    - dbt_baskets_sum_of_item_profit
spaceSlug: "-sales"
version: 1
downloadedAt: "2026-03-09T14:59:04.061Z"
