chartConfig:
  config:
    eChartsConfig:
      grid:
        bottom: 15px
        containLabel: true
        left: 5px
        right: 5px
        top: 5px
      series:
        - encode:
            xRef:
              field: dbt_orders_order_date_quarter
            yRef:
              field: average_orders_per_user
          isFilteredOut: false
          label:
            position: bottom
            show: true
          showSymbol: true
          type: line
          yAxisIndex: 0
      showAxisTicks: false
      xAxis:
        - name: " "
      yAxis:
        - name: ""
        - name: ""
    layout:
      flipAxes: false
      showGridY: false
      showYAxis: false
      xField: dbt_orders_order_date_quarter
      yField:
        - average_orders_per_user
  type: cartesian
contentType: chart
description: "Line chart showing average orders per quarter per user "
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_order_date_quarter
  exploreName: dbt_orders
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_count_distinct_user_id
    - dbt_orders_count_distinct_order_id
  sorts:
    - descending: true
      fieldId: dbt_orders_order_date_quarter
  tableCalculations:
    - displayName: average orders per user
      name: average_orders_per_user
      sql: ROUND(${dbt_orders.order_id}/${dbt_orders.count_distinct_user_id}, 2)
name: What's the average number of quarterly orders per user?
slug: average-quarterly-orders-per-user
spaceSlug: shared
tableConfig:
  columnOrder:
    - dbt_orders_order_date_quarter
    - dbt_orders_count_distinct_user_id
    - dbt_orders_count_distinct_order_id
    - average_orders_per_user
tableName: dbt_orders
verification: null
version: 1
