chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: true
        type: scroll
      series:
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_average_of_basket_total
          isFilteredOut: false
          name: Average Order Value
          type: line
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_profit_margin
          isFilteredOut: false
          name: Profit Margin (%)
          type: line
          yAxisIndex: 1
      showAxisTicks: false
      xAxis:
        - name: Order month
      yAxis:
        - name: Average Order Value
        - name: Profit Margin (%)
    layout:
      xField: dbt_orders_order_date_month
      yField:
        - dbt_orders_average_of_basket_total
        - dbt_orders_profit_margin
  type: cartesian
contentType: chart
dashboardSlug: sales-dashboard-test
description: >-
  Monthly trend of Average Order Value and Profit Margin (%). Uses a secondary
  Y-axis for Profit Margin (%).
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_order_date_month
  exploreName: dbt_orders
  filters:
    dimensions:
      and: []
      id: ee370a85-ef2c-497f-82d1-05683f8412e8
    metrics:
      and: []
      id: 3f5378cc-5d4b-4f52-bff6-cfbff17a46bb
    tableCalculations:
      and: []
      id: c0bae632-78bf-4fdb-adc3-49f638d496be
  limit: 1000
  metricOverrides: {}
  metrics:
    - dbt_orders_average_of_basket_total
    - dbt_orders_profit_margin
  sorts:
    - descending: false
      fieldId: dbt_orders_order_date_month
  tableCalculations: []
name: Average Order Value vs Profit Margin (%) by Month
slug: average-order-value-vs-profit-margin-by-month
spaceSlug: test-space
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_average_of_basket_total
    - dbt_orders_profit_margin
tableName: dbt_orders
verification: null
version: 1
