chartConfig:
  config:
    columns: {}
    conditionalFormattings: []
    hideRowNumbers: false
    metricsAsRows: false
    showColumnCalculation: false
    showResultsTotal: false
    showRowCalculation: false
    showSubtotals: false
    showTableNames: true
  type: table
contentType: chart
dashboardSlug: customer-feedback-support-dashboard
description: Displays the average feedback rating from customers on support requests.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions: []
  exploreName: dbt_support_requests
  filters:
    dimensions:
      and: []
      id: 01e66153-ecfc-41bf-baab-3c27aaa16e1a
    metrics:
      and: []
      id: 095616eb-fd1c-47f6-a405-78f3fa8cbbf2
    tableCalculations:
      and: []
      id: 031d156c-e2b3-4c29-b2f4-8639f1baaa50
  limit: 1
  metricOverrides: {}
  metrics:
    - dbt_support_requests_average_of_feedback_rating
  sorts: []
  tableCalculations: []
name: Average Customer Feedback Rating
slug: average-customer-feedback-rating
spaceSlug: "-key-company-dashboards"
tableConfig:
  columnOrder:
    - dbt_support_requests_average_of_feedback_rating
tableName: dbt_support_requests
verification: null
version: 1
