chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: true
        type: plain
      series:
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_average_of_basket_total
          name: Average of basket total
          type: line
          yAxisIndex: 0
      xAxis:
        - name: Order Month
      yAxis:
        - name: Average Order Value
    layout:
      xField: dbt_orders_order_date_month
      yField:
        - dbt_orders_average_of_basket_total
  type: cartesian
contentType: chart
dashboardSlug: redwood-ranch-partner-performance-dashboard
description: Tracks the average value of each order from Redwood Ranch over time.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - dbt_orders_order_date_month
  exploreName: dbt_orders
  filters:
    dimensions:
      and:
        - id: e7de7d1a-c881-4f53-9702-0ce3ea47e64b
          operator: equals
          target:
            fieldId: dbt_orders_partner_name
          values:
            - Redwood Ranch
      id: f60f5257-f2eb-4661-a7a8-d411f11578af
    metrics:
      and: []
      id: 33a8f4ae-6fcd-492e-86c1-54e7e9d65aab
  limit: 36
  metricOverrides: {}
  metrics:
    - dbt_orders_average_of_basket_total
  sorts:
    - descending: false
      fieldId: dbt_orders_order_date_month
  tableCalculations: []
name: Average Order Value by Month (Redwood Ranch)
slug: average-order-value-by-month-redwood-ranch
spaceSlug: sql-runner-space
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_average_of_basket_total
tableName: dbt_orders
verification: null
version: 1
