chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: true
        type: scroll
      series:
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_average_of_basket_total
          isFilteredOut: false
          name: Average Order Value
          type: line
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_profit
          isFilteredOut: false
          name: Profit
          type: line
          yAxisIndex: 1
      showAxisTicks: false
      xAxis:
        - name: Order Month
      yAxis:
        - name: Average Order Value
        - name: Profit
    layout:
      xField: dbt_orders_order_date_month
      yField:
        - dbt_orders_average_of_basket_total
        - dbt_orders_sum_of_profit
  type: cartesian
contentType: chart
dashboardSlug: order-revenue-dashboard
description: Tracks monetization efficiency (AOV) alongside total profit over time.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_order_date_month
  exploreName: dbt_orders
  filters:
    dimensions:
      and: []
      id: 86468772-f609-4bfc-b99d-58d2a2e82ef2
    metrics:
      and: []
      id: 78cc3a81-a592-4d6f-9f71-9b6499e94553
    tableCalculations:
      and: []
      id: 0314df2b-485f-4df1-8722-b49fca6a5025
  limit: 1000
  metricOverrides: {}
  metrics:
    - dbt_orders_average_of_basket_total
    - dbt_orders_sum_of_profit
  sorts:
    - descending: false
      fieldId: dbt_orders_order_date_month
  tableCalculations: []
name: Average Order Value & Profit by month
slug: average-order-value-profit-by-month
spaceSlug: shared
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_average_of_basket_total
    - dbt_orders_sum_of_profit
tableName: dbt_orders
verification: null
version: 1
