chartConfig:
  config:
    eChartsConfig: {}
    layout: {}
  type: cartesian
contentType: chart
dashboardSlug: dashboard-with-tabs-test-saving-to
description: ""
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - dbt_support_requests_browser
  exploreName: dbt_support_requests
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_support_requests_average_of_feedback_rating
  sorts:
    - descending: false
      fieldId: dbt_support_requests_browser
  tableCalculations: []
name: browser new tab 2
slug: browser-new-tab-2
spaceSlug: "-sales"
tableConfig:
  columnOrder:
    - dbt_support_requests_browser
    - dbt_support_requests_average_of_feedback_rating
tableName: dbt_support_requests
verification: null
version: 1
