chartConfig:
  config:
    groupColorOverrides: {}
    groupFieldIds:
      - dbt_orders_order_date_period
    groupLabelOverrides: {}
    groupSortOverrides: []
    groupValueOptionOverrides: {}
    isDonut: true
    legendMaxItemLength: 30
    legendPosition: horizontal
    metricId: dbt_orders_sum_of_profit
    showLegend: true
    showPercentage: false
    showValue: true
    valueLabel: inside
  type: pie
contentType: chart
dashboardSlug: period-over-period-parameters-example
description: ""
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - dbt_orders_order_date_period
  exploreName: dbt_orders
  filters:
    dimensions:
      and:
        - id: b8cbcfb6-1972-4855-af32-4b5cfc5e49a5
          operator: notEquals
          required: false
          target:
            fieldId: dbt_orders_order_date_period
          values:
            - out of range
            - previous year
      id: 4a0556da-4002-432e-b736-4f5f89a0bf7e
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_sum_of_profit
  sorts:
    - descending: false
      fieldId: dbt_orders_order_date_period
  tableCalculations: []
name: Total profit current period vs. previous period
parameters:
  dbt_orders.date_range: last 7 days
slug: >-
  copy-of-total-orders-during-current-period-vs-previous-period-and-year-1762297425191
spaceSlug: shared
tableConfig:
  columnOrder:
    - dbt_orders_order_date_period
    - dbt_orders_sum_of_profit
tableName: dbt_orders
verification: null
version: 1
