chartConfig:
  config:
    customLabel: Total Orders
    max: 10000
    min: 0
    sections:
      - color: "#d97060"
        max: 5000
        min: 0
      - color: "#e8b840"
        max: 8000
        min: 5000
      - color: "#6cd186"
        max: 10000
        min: 8000
    selectedField: dbt_orders_count_distinct_order_id
    showAxisLabels: true
  type: gauge
contentType: chart
description: ""
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_order_date_month
  exploreName: dbt_orders
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_count_distinct_order_id
    - dbt_orders_average_of_basket_total
  sorts:
    - descending: true
      fieldId: dbt_orders_count_distinct_order_id
  tableCalculations: []
name: Our total orders gauge
slug: copy-of-how-many-orders-have-we-fulfilled-1765193680327
spaceSlug: "-sales"
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_count_distinct_order_id
    - dbt_orders_average_of_basket_total
tableName: dbt_orders
verification: null
version: 1
