chartConfig:
  config:
    columns: {}
    conditionalFormattings: []
    hideRowNumbers: false
    metricsAsRows: false
    showColumnCalculation: false
    showResultsTotal: false
    showRowCalculation: false
    showTableNames: false
  type: table
contentType: chart
description: How much revenue are we making each week?
metricQuery:
  additionalMetrics:
    - description: >-
        Count distinct of User id on the table Dbt orders. Lightdash has created
        this metric automatically.
      label: Count distinct of User id
      name: user_id_count_distinct
      sql: ${TABLE}.user_id
      table: dbt_orders
      type: count_distinct
      uuid: 86c74047-ab95-4549-a356-75292ac3e9cc
    - description: >-
        Count distinct of Order id on the table Dbt orders. Lightdash has
        created this metric automatically.
      label: Count distinct of Order id
      name: order_id_count_distinct
      sql: ${TABLE}.order_id
      table: dbt_orders
      type: count_distinct
      uuid: 5174f003-50da-41b3-aef8-ebba9598bf07
    - description: >-
        Count distinct of Partner id on the table Dbt orders. Lightdash has
        created this metric automatically.
      label: Count distinct of Partner id
      name: partner_id_count_distinct
      sql: ${TABLE}.partner_id
      table: dbt_orders
      type: count_distinct
      uuid: 77ea0e40-939e-48bf-8083-e26d6b8e853e
    - description: Sum of Basket total on the table Dbt orders
      label: Sum of Basket total
      name: basket_total_sum
      sql: ${TABLE}.basket_total
      table: dbt_orders
      type: sum
      uuid: c1b63e3b-bc8e-418e-bae5-205c36e8ce9e
  customDimensions: []
  dimensions:
    - dbt_orders_order_date_week
    - dbt_orders_user_id
  exploreName: dbt_orders
  filters: {}
  limit: 500
  metrics:
    - dbt_orders_sum_of_basket_total
    - dbt_orders_average_of_basket_total
  sorts:
    - descending: true
      fieldId: dbt_orders_order_date_week
  tableCalculations: []
name: Copy of How much revenue are we making each week?
pivotConfig:
  columns:
    - dbt_orders_order_date_week
slug: copy-of-how-much-revenue-are-we-making-each-week-
spaceSlug: "-sales"
tableConfig:
  columnOrder:
    - dbt_orders_order_date_week
    - dbt_orders_user_id
    - dbt_orders_sum_of_basket_total
    - dbt_orders_average_of_basket_total
tableName: dbt_orders
verification: null
version: 1
