chartConfig:
  config:
    comparisonFormat: raw
    flipColors: false
    selectedField: percent_change_from_previous_of_sum_of_basket_total
    showBigNumberLabel: true
    showComparison: true
    showTableNamesInLabel: false
  type: big_number
contentType: chart
dashboardSlug: a-bunch-of-markdown-and-big-values
description: ""
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - dbt_orders_order_date_month
  exploreName: dbt_orders
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_sum_of_basket_total
  sorts:
    - descending: true
      fieldId: dbt_orders_order_date_month
  tableCalculations:
    - displayName: Percent change from previous of Sum of basket total
      format:
        round: 2
        type: percent
      name: percent_change_from_previous_of_sum_of_basket_total
      template:
        fieldId: dbt_orders_sum_of_basket_total
        orderBy:
          - fieldId: dbt_orders_order_date_month
            order: asc
        type: percent_change_from_previous
name: Copy of total pct change
slug: copy-of-total-pct-change-1763179607904
spaceSlug: "-sales"
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_sum_of_basket_total
    - percent_change_from_previous_of_sum_of_basket_total
tableName: dbt_orders
verification: null
version: 1
