chartConfig:
  config:
    comparisonFormat: raw
    comparisonLabel: MoM
    flipColors: false
    label: Profit
    selectedField: dbt_orders_sum_of_profit
    showBigNumberLabel: true
    showComparison: true
    showTableNamesInLabel: true
  type: big_number
contentType: chart
description: "The total revenue we get every month from all customers "
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_order_date_month
  exploreName: dbt_orders
  filters:
    dimensions:
      and:
        - id: fecaec2a-1397-401b-8d36-ad6de29b9b31
          operator: equals
          required: false
          target:
            fieldId: dbt_orders_browser
          values:
            - chrome
      id: 19e1ded6-673f-4fc5-9248-d76b07e812a3
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_sum_of_profit
  sorts:
    - descending: true
      fieldId: dbt_orders_order_date_month
  tableCalculations: []
name: Copy of What is our total revenue this month?
slug: copy-of-what-is-our-total-revenue-this-month-1768328685592
spaceSlug: "-sales"
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_sum_of_profit
tableName: dbt_orders
verification: null
version: 1
