chartConfig:
  config:
    columns: {}
    conditionalFormattings: []
    hideRowNumbers: false
    metricsAsRows: false
    showColumnCalculation: false
    showResultsTotal: false
    showRowCalculation: false
    showSubtotals: false
    showTableNames: true
  type: table
contentType: chart
dashboardSlug: customer-success-dashboard
description: >-
  Average customer satisfaction rating from post-support surveys. Measures
  overall customer happiness with support interactions.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions: []
  exploreName: dbt_support_requests
  filters:
    dimensions:
      and: []
      id: e57449a1-102d-429d-ab77-3f28cee2d13d
    metrics:
      and: []
      id: 06d50cb0-1923-4bac-ba0c-047f6c883052
    tableCalculations:
      and: []
      id: 60becb12-a9a6-4a81-b061-c0c93f5fb010
  limit: 1000
  metricOverrides: {}
  metrics:
    - dbt_support_requests_average_of_feedback_rating
  sorts: []
  tableCalculations: []
name: Customer Satisfaction Score
slug: customer-satisfaction-score
spaceSlug: shared
tableConfig:
  columnOrder:
    - dbt_support_requests_average_of_feedback_rating
tableName: dbt_support_requests
verification: null
version: 1
