chartConfig:
  config:
    spec:
      $schema: https://vega.github.io/schema/vega-lite/v6.json
      config:
        axis:
          grid: true
        view:
          stroke: null
      encoding:
        tooltip:
          - field: dbt_orders_order_date_month
            timeUnit: yearmonth
            title: Month
            type: temporal
          - field: dbt_orders_sum_of_profit
            format: $,.0f
            title: Profit (Mean)
            type: quantitative
          - field: profit_low
            format: $,.0f
            title: Profit (Low)
            type: quantitative
          - field: profit_high
            format: $,.0f
            title: Profit (High)
            type: quantitative
        x:
          field: dbt_orders_order_date_month
          timeUnit: yearmonth
          title: Month
          type: temporal
      height: 300
      layer:
        - encoding:
            color:
              value: "#d1b3ff"
            "y":
              field: profit_low
              type: quantitative
            y2:
              field: profit_high
          mark:
            type: errorband
        - encoding:
            color:
              value: "#7c43bd"
            "y":
              axis:
                format: $,.0f
              field: dbt_orders_sum_of_profit
              title: Profit
              type: quantitative
          mark:
            type: line
      title: Monthly profit with confidence intervals
      width: container
  type: custom
contentType: chart
description: ""
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - dbt_orders_order_date_month
    - dbt_orders_order_date_month_num
  exploreName: dbt_orders
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_sum_of_profit
  sorts:
    - descending: true
      fieldId: dbt_orders_order_date_month
  tableCalculations:
    - displayName: profit high
      format:
        separator: default
        type: default
      name: profit_high
      sql: ${dbt_orders.sum_of_profit}+${dbt_orders.order_date_month_num}*1500
      type: number
    - displayName: profit low
      format:
        separator: default
        type: default
      name: profit_low
      sql: >-
        greatest(0,${dbt_orders.sum_of_profit}-(15 -
        ${dbt_orders.order_date_month_num})*1333)
      type: number
name: Example custom chart with confidence interval
slug: example-custom-chart-with-confidence-interval
spaceSlug: shared/custom-visuals
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_order_date_month_num
    - dbt_orders_sum_of_profit
    - profit_high
    - profit_low
tableName: dbt_orders
verification: null
version: 1
