chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: dbt_support_requests_order_date_month
            yRef:
              field: dbt_support_requests_count_distinct_request_id
              pivotValues:
                - field: dbt_support_requests_reason
                  value: Delivery issue
          isFilteredOut: false
          stack: dbt_support_requests_count_distinct_request_id
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_support_requests_order_date_month
            yRef:
              field: dbt_support_requests_count_distinct_request_id
              pivotValues:
                - field: dbt_support_requests_reason
                  value: Payment issue
          isFilteredOut: false
          stack: dbt_support_requests_count_distinct_request_id
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_support_requests_order_date_month
            yRef:
              field: dbt_support_requests_count_distinct_request_id
              pivotValues:
                - field: dbt_support_requests_reason
                  value: Product related query
          isFilteredOut: false
          stack: dbt_support_requests_count_distinct_request_id
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_support_requests_order_date_month
            yRef:
              field: dbt_support_requests_count_distinct_request_id
              pivotValues:
                - field: dbt_support_requests_reason
                  value: Wrong item received
          isFilteredOut: false
          stack: dbt_support_requests_count_distinct_request_id
          type: bar
          yAxisIndex: 0
      showAxisTicks: false
      tooltip: |-
        <strong>Total Feedback Rating:</strong>
        ${total_feedback_rating}
        </br>
    layout:
      stack: stack
      xField: dbt_support_requests_order_date_month
      yField:
        - dbt_support_requests_count_distinct_request_id
  type: cartesian
contentType: chart
description: >-
  The chart illustrates the relationship between the total amount spent in
  baskets and the number of distinct support requests submitted.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - dbt_support_requests_reason
    - dbt_support_requests_order_date_month
  exploreName: dbt_support_requests
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_support_requests_count_distinct_request_id
  sorts:
    - descending: true
      fieldId: dbt_support_requests_order_date_month
  tableCalculations:
    - displayName: monthly_total_requests
      format:
        separator: default
        type: default
      name: monthly_total_requests
      sql: >-
        sum(${dbt_support_requests.count_distinct_request_id}) over(partition by
        ${dbt_support_requests.order_date_month})
      type: number
    - displayName: percentage_of_total_requests
      format:
        separator: default
        type: percent
      name: percentage_of_total_requests
      sql: >-
        ${dbt_support_requests.count_distinct_request_id}/
        ${monthly_total_requests}
      type: number
name: How does the Basket Total correlate with Total Support Requests?
pivotConfig:
  columns:
    - dbt_support_requests_reason
slug: how-does-the-basket-total-correlate-with-total-support-requests
spaceSlug: shared/shared-nested/jess-s-space
tableConfig:
  columnOrder:
    - dbt_support_requests_reason
    - dbt_support_requests_order_date_month
    - dbt_support_requests_count_distinct_request_id
    - monthly_total_requests
    - percentage_of_total_requests
tableName: dbt_support_requests
verification: null
version: 1
