chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: dbt_users_created_date_month
            yRef:
              field: dbt_users_count_distinct_of_user_id
          isFilteredOut: false
          label:
            position: top
            show: true
          markLine:
            data:
              - label:
                  formatter: "average: {c}"
                  position: end
                lineStyle:
                  color: "#000"
                name: average
                type: average
                uuid: fb478e3a-16fd-4419-948c-0cbcdf4106b4
            lineStyle:
              color: "#000"
              type: solid
              width: 3
            symbol: none
          type: bar
          yAxisIndex: 0
      showAxisTicks: true
      tooltip: ""
      xAxis:
        - name: Date (week)
      yAxis:
        - name: Number of new users
        - {}
    layout:
      flipAxes: false
      showGridY: false
      showYAxis: true
      stack: none
      xField: dbt_users_created_date_month
      yField:
        - dbt_users_count_distinct_of_user_id
  type: cartesian
contentType: chart
description: >-
  This chart shows how many users were created each month over the given time
  period.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_users_created_date_month
  exploreName: dbt_users
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_users_count_distinct_of_user_id
  sorts:
    - descending: true
      fieldId: dbt_users_created_date_month
  tableCalculations: []
name: How many users were created each month?
slug: how-many-users-were-created-each-week-
spaceSlug: "-sales"
tableConfig:
  columnOrder:
    - dbt_users_created_date_month
    - dbt_users_count_distinct_of_user_id
tableName: dbt_users
verification: null
version: 1
