chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: dbt_orders_order_date_week
            yRef:
              field: dbt_orders_sum_of_basket_total
          isFilteredOut: false
          label:
            position: top
            show: true
            showLabel: false
            showSeriesName: false
            showValue: true
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_week
            yRef:
              field: dbt_orders_sum_of_basket_total__pop__week_1__ioxhd1
          isFilteredOut: false
          label:
            position: inside
            show: true
            showLabel: false
            showSeriesName: false
            showValue: true
          type: bar
          yAxisIndex: 0
      showAxisTicks: false
    layout:
      xField: dbt_orders_order_date_week
      yField:
        - dbt_orders_sum_of_basket_total
        - dbt_orders_sum_of_basket_total__pop__week_1__ioxhd1
  type: cartesian
contentType: chart
dashboardSlug: "-kpi-dashboard"
description: >-
  Weekly revenue comparison showing current week performance against the prior
  week to identify growth or decline trends.
metricQuery:
  additionalMetrics:
    - baseMetricId: dbt_orders_sum_of_basket_total
      description: Total sales revenue from all orders.
      generationType: periodOverPeriod
      granularity: WEEK
      hidden: true
      label: Revenue (Previous week)
      name: sum_of_basket_total__pop__week_1__ioxhd1
      periodOffset: 1
      sql: ${TABLE}.basket_total
      table: dbt_orders
      timeDimensionId: dbt_orders_order_date_week
      type: sum
      uuid: 4beb8f70-a1dc-4db6-83dd-7e4329d9a7da
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_order_date_week
  exploreName: dbt_orders
  filters:
    dimensions:
      and:
        - id: 2d625a94-38bc-4753-b29b-2db938d97b9a
          operator: inThePast
          required: false
          settings:
            completed: false
            unitOfTime: weeks
          target:
            fieldId: dbt_orders_order_date_week
          values:
            - 10
      id: d600c2bc-79e4-4813-bb39-74bb483fe96d
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_sum_of_basket_total
    - dbt_orders_sum_of_basket_total__pop__week_1__ioxhd1
  sorts:
    - descending: true
      fieldId: dbt_orders_sum_of_basket_total
  tableCalculations: []
name: How does revenue this week compare to the previous week?
slug: how-does-revenue-this-week-compare-to-the-previous-week
spaceSlug: "-key-company-dashboards"
tableConfig:
  columnOrder:
    - dbt_orders_order_date_week
    - dbt_orders_sum_of_basket_total
    - dbt_orders_sum_of_basket_total__pop__week_1__ioxhd1
tableName: dbt_orders
verification: null
version: 1
