chartConfig:
  config:
    columns:
      dbt_orders_avg_profit:
        visible: true
      dbt_orders_median_profit:
        visible: true
      dbt_orders_count_distinct_order_id:
        visible: true
      dbt_orders_sum_of_profit:
        visible: true
    conditionalFormattings: []
    hideRowNumbers: false
    metricsAsRows: false
    showColumnCalculation: false
    showResultsTotal: false
    showRowCalculation: false
    showSubtotals: false
    showTableNames: false
  type: table
contentType: chart
description: >-
  This table breaks down order metrics including order volume, profit, average
  order value, and profit percentiles across different browsers and partners,
  enabling performance comparison and identification of top-performing
  combinations.
metricQuery:
  additionalMetrics: []
  customDimensions:
    - dimensionType: string
      id: partner_broswer
      name: partner+browser
      sql: concat(${dbt_orders.partner_name}, '-', ${dbt_orders.browser})
      table: dbt_orders
      type: sql
  dimensionOverrides: {}
  dimensions:
    - partner_broswer
    - dbt_orders_partner_name
    - dbt_orders_browser
  exploreName: dbt_orders
  filters: {}
  limit: 1000
  metricOverrides: {}
  metrics:
    - dbt_orders_avg_profit
    - dbt_orders_median_profit
    - dbt_orders_count_distinct_order_id
    - dbt_orders_sum_of_profit
  sorts:
    - descending: false
      fieldId: partner_broswer
    - descending: false
      fieldId: dbt_orders_partner_name
    - descending: false
      fieldId: dbt_orders_browser
  tableCalculations:
    - displayName: Count Distinct Partner Browser
      format:
        separator: default
        type: number
      name: count_distinct_partner_browser
      sql: COUNT(DISTINCT ${partner_broswer}) over()
      type: number
name: >-
  How do order volume, profit, and customer spending vary by browser and
  partner?
pivotConfig:
  columns:
    - partner_broswer
slug: how-do-order-volume-profit-and-customer-spending-vary-by-browser-and-partner
spaceSlug: shared/shared-nested/jess-s-space
tableConfig:
  columnOrder:
    - partner_broswer
    - dbt_orders_partner_name
    - dbt_orders_browser
    - dbt_orders_avg_profit
    - dbt_orders_median_profit
    - dbt_orders_count_distinct_order_id
    - dbt_orders_sum_of_profit
    - count_distinct_partner_browser
tableName: dbt_orders
verification: null
version: 1
