chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_profit
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Roots & Shoots
          isFilteredOut: false
          stack: dbt_orders_sum_of_profit
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_profit
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Trowels R Us
          isFilteredOut: false
          stack: dbt_orders_sum_of_profit
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_profit
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Potted Paradise
          isFilteredOut: false
          stack: dbt_orders_sum_of_profit
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_profit
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Redwood Ranch
          isFilteredOut: false
          stack: dbt_orders_sum_of_profit
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_profit
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Happy Harvesters
          isFilteredOut: false
          stack: dbt_orders_sum_of_profit
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_profit
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Plant Paradise
          isFilteredOut: false
          stack: dbt_orders_sum_of_profit
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_profit
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Peat, Fruits and Leaves
          isFilteredOut: false
          stack: dbt_orders_sum_of_profit
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_profit
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Garden of Sweden
          isFilteredOut: false
          stack: dbt_orders_sum_of_profit
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_profit
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Sprout Society
          isFilteredOut: false
          stack: dbt_orders_sum_of_profit
          type: bar
          yAxisIndex: 0
      showAxisTicks: false
    layout:
      stack: stack
      xField: dbt_orders_order_date_month
      yField:
        - dbt_orders_sum_of_profit
  type: cartesian
contentType: chart
dashboardSlug: pre-aggregates-sneak-peek
description: >-
  Stacked monthly profit comparison showing contribution from each partner
  throughout the current year to identify seasonal patterns and partner
  performance trends.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_order_date_month
    - dbt_orders_partner_name
  exploreName: dbt_orders
  filters:
    dimensions:
      and:
        - id: bb1769c2-c339-4abe-b4c7-db5641864283
          operator: inTheCurrent
          required: false
          settings:
            completed: false
            unitOfTime: years
          target:
            fieldId: dbt_orders_order_date
          values:
            - 1
      id: 44a50e4f-865d-474b-a819-ab56287df654
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_sum_of_profit
  sorts:
    - descending: true
      fieldId: dbt_orders_order_date_month
  tableCalculations: []
name: How does monthly profit trend across partners in the current year?
pivotConfig:
  columns:
    - dbt_orders_partner_name
slug: how-does-monthly-profit-trend-across-partners-in-the-current-year
spaceSlug: shared/dashcachedemo
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_partner_name
    - dbt_orders_sum_of_profit
tableName: dbt_orders
verification: null
version: 1
