chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_basket_total
          isFilteredOut: false
          type: line
          yAxisIndex: 0
      showAxisTicks: false
    layout:
      flipAxes: false
      stack: none
      xField: dbt_orders_order_date_month
      yField:
        - dbt_orders_sum_of_basket_total
  type: cartesian
contentType: chart
description: >-
  Revenue trend line showing total sales revenue by month over the past 6
  months, revealing seasonal patterns and growth trajectory.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_order_date_month
  exploreName: dbt_orders
  filters:
    dimensions:
      and:
        - id: 11aa341e-7cfe-4017-8cee-69d3e3a4760c
          operator: inThePast
          required: false
          settings:
            completed: false
            unitOfTime: months
          target:
            fieldId: dbt_orders_order_date_month
          values:
            - 6
      id: 8c3b59b1-7738-4de7-a331-377ba21ead35
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_sum_of_basket_total
  sorts:
    - descending: true
      fieldId: dbt_orders_order_date_month
  tableCalculations: []
name: How has revenue trended over the past 6 months?
slug: how-has-revenue-trended-over-the-past-6-months
spaceSlug: test-space
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_sum_of_basket_total
tableName: dbt_orders
verification: null
version: 1
