chartConfig:
  config:
    columns: {}
    conditionalFormattings:
      - color: "#8b8cf6"
        rules:
          - compareTarget:
              fieldId: dbt_orders_profit_average_of_profit
            id: 7436ed57-6f45-4f76-90d1-48513b476e67
            operator: lessThan
        target:
          fieldId: dbt_orders_profit_median_of_profit
    hideRowNumbers: false
    metricsAsRows: false
    showColumnCalculation: false
    showResultsTotal: false
    showRowCalculation: false
    showSubtotals: false
    showTableNames: false
  type: table
contentType: chart
description: >-
  Monthly comparison of average and median profit values for orders placed in
  the past 12 months, with conditional highlighting when median profit falls
  below average profit.
metricQuery:
  additionalMetrics:
    - baseDimensionName: profit
      description: "Average of Profit on the table Orders "
      formatOptions:
        separator: default
        type: default
      label: Average of Profit
      name: profit_average_of_profit
      round: 2
      sql: ${TABLE}.profit
      table: dbt_orders
      type: average
      uuid: bce5bdcb-7f18-4ee5-8f91-db07663a5716
    - baseDimensionName: profit
      description: "Median of Profit on the table Orders "
      formatOptions:
        separator: default
        type: default
      label: Median of Profit
      name: profit_median_of_profit
      sql: ${TABLE}.profit
      table: dbt_orders
      type: median
      uuid: d5d594bc-a02e-4316-8456-29838af0b4cc
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_order_date_month
  exploreName: dbt_orders
  filters:
    dimensions:
      and:
        - id: 25ef3a08-01b9-4bb3-9ad0-8284f408f29e
          operator: inThePast
          required: false
          settings:
            completed: true
            unitOfTime: months
          target:
            fieldId: dbt_orders_order_date
          values:
            - 12
      id: c7523978-b637-41c7-8ebb-eb4085121d4d
  limit: 5000
  metricOverrides: {}
  metrics:
    - dbt_orders_profit_average_of_profit
    - dbt_orders_profit_median_of_profit
  sorts:
    - descending: true
      fieldId: dbt_orders_order_date_month
  tableCalculations: []
name: How do average and median profit compare by order month in the past 12 months?
pivotConfig:
  columns:
    - dbt_orders_order_date_month
slug: how-do-average-and-median-profit-compare-by-order-month-in-the-past-12-months
spaceSlug: shared
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_profit_average_of_profit
    - dbt_orders_profit_median_of_profit
tableName: dbt_orders
verification: null
version: 1
