chartConfig:
  config:
    groupColorOverrides:
      Garden of Sweden: "#ffc658"
      Happy Harvesters: "#8b8cf6"
      Peat, Fruits and Leaves: "#5dd9d2"
      Plant Paradise: "#ff7eb9"
      Potted Paradise: "#7cde96"
    groupFieldIds:
      - dbt_baskets_partner_name
    groupLabelOverrides: {}
    groupSortOverrides: []
    groupValueOptionOverrides: {}
    isDonut: true
    legendMaxItemLength: 30
    legendPosition: horizontal
    metricId: dbt_baskets_sum_of_basket_total
    showLegend: true
    showPercentage: true
    showValue: true
    valueLabel: outside
  type: pie
contentType: chart
dashboardSlug: lightdash-dashboard-1
description: >-
  Revenue distribution by partner name (Garden of Sweden, Happy Harvesters, Peat
  Fruits and Leaves, Plant Paradise, Potted Paradise) shows which partners
  generate the largest share of total basket sales.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - dbt_baskets_partner_name
  exploreName: dbt_baskets
  filters:
    dimensions:
      and:
        - id: cf1fed57-c345-4ed6-845f-5f4af44fd022
          operator: equals
          required: false
          target:
            fieldId: dbt_baskets_partner_name
          values:
            - Garden of Sweden
            - Happy Harvesters
            - Peat, Fruits and Leaves
            - Plant Paradise
            - Potted Paradise
      id: 47e48ae5-697d-45ab-91b1-5a56ea5ceb2c
  limit: 500
  metricOverrides:
    dbt_baskets_sum_of_basket_total:
      formatOptions:
        compact: millions
        round: 2
        separator: default
        type: number
  metrics:
    - dbt_baskets_sum_of_basket_total
  sorts:
    - descending: false
      fieldId: dbt_baskets_partner_name
  tableCalculations: []
name: How does basket total revenue compare across the five partner companies?
slug: >-
  how-does-basket-total-revenue-compare-across-the-five-partner-companies-1768203909741
spaceSlug: shared
tableConfig:
  columnOrder:
    - dbt_baskets_partner_name
    - dbt_baskets_sum_of_basket_total
tableName: dbt_baskets
verification: null
version: 1
