chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_basket_total
          isFilteredOut: false
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_average_of_basket_total
          isFilteredOut: false
          type: line
          yAxisIndex: 1
      showAxisTicks: false
      xAxis:
        - name: Month
          type: category
      yAxis:
        - name: Revenue
    layout:
      xField: dbt_orders_order_date_month
      yField:
        - dbt_orders_sum_of_basket_total
        - dbt_orders_average_of_basket_total
  type: cartesian
contentType: chart
description: Monthly revenue trend showing total basket revenue over time
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_order_date_month
  exploreName: dbt_orders
  filters: {}
  limit: 500
  metricOverrides:
    dbt_orders_average_of_basket_total:
      formatOptions:
        currency: USD
        round: 0
        separator: default
        type: currency
    dbt_orders_sum_of_basket_total:
      formatOptions:
        compact: thousands
        currency: USD
        round: 0
        separator: default
        type: currency
  metrics:
    - dbt_orders_sum_of_basket_total
    - dbt_orders_average_of_basket_total
  sorts:
    - descending: false
      fieldId: dbt_orders_order_date_month
  tableCalculations: []
name: How much revenue are we making each month?
slug: how-much-revenue-are-we-making-each-week-
spaceSlug: "-sales"
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_sum_of_basket_total
    - dbt_orders_average_of_basket_total
tableName: dbt_orders
verification: null
version: 1
