chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_count_distinct_order_id
              pivotValues:
                - field: is_gmail_email
                  value: false
          isFilteredOut: false
          label:
            position: top
            show: true
          name: Other users
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_count_distinct_order_id
              pivotValues:
                - field: is_gmail_email
                  value: true
          isFilteredOut: false
          label:
            position: top
            show: true
          name: Gmail users
          type: bar
          yAxisIndex: 0
      yAxis:
        - name: Total orders
        - {}
    layout:
      xField: dbt_orders_order_date_month
      yField:
        - dbt_orders_count_distinct_order_id
  type: cartesian
contentType: chart
description: >-
  Shows the split per month of orders by those with gmail emails compared to
  those with other email domains
metricQuery:
  additionalMetrics:
    - baseDimensionName: partner_id
      description: "Count distinct of Partner id on the table Orders "
      formatOptions:
        separator: default
        type: default
      label: Total unique partners
      name: partner_id_total_unique_partners
      sql: ${TABLE}.partner_id
      table: dbt_orders
      type: count_distinct
      uuid: a56bd4f3-87d9-4e03-9434-7bc8b724ff6d
    - baseDimensionName: order_id
      description: >-
        Count distinct of Order id on the table Orders with filters
        dbt_orders.shipping_country
      filters:
        - id: 37de7792-dc99-4144-bd85-9f79d0b5ef0a
          operator: equals
          target:
            fieldRef: dbt_orders.shipping_country
          values:
            - US
      formatOptions:
        separator: default
        type: default
      label: Orders to US
      name: order_id_orders_to_u_s
      sql: ${TABLE}.order_id
      table: dbt_orders
      type: count_distinct
      uuid: 5cfb35f3-c6c9-452e-bd5b-ad1c64b82c94
    - baseDimensionName: order_id
      description: >-
        Count distinct of Order id on the table Orders with filters
        dbt_orders.shipping_country
      filters:
        - id: 6e120274-2a97-455e-95eb-8b619688b768
          operator: equals
          target:
            fieldRef: dbt_orders.shipping_country
          values:
            - GB
      formatOptions:
        separator: default
        type: default
      label: Orders to GB
      name: order_id_orders_to_g_b
      sql: ${TABLE}.order_id
      table: dbt_orders
      type: count_distinct
      uuid: d8681a1a-fd0b-4e7d-bec9-3a21b0cc0a56
  customDimensions:
    - binType: fixed_width
      binWidth: 5
      dimensionId: dbt_orders_profit
      id: profit_profit_binned
      name: Profit Binned
      table: dbt_orders
      type: bin
    - dimensionType: boolean
      id: is_gmail_email
      name: is_gmail_email
      sql: case when email like '%gmail%' then true else false end
      table: dbt_orders
      type: sql
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_order_date_month
    - is_gmail_email
  exploreName: dbt_orders
  filters:
    dimensions:
      and:
        - id: 41d1aa03-bed7-455d-8fa2-773eae32249b
          operator: inThePast
          required: false
          settings:
            completed: true
            unitOfTime: months
          target:
            fieldId: dbt_orders_order_date_month
          values:
            - 12
      id: 998b33c5-670b-4534-a821-ee5b2a260a68
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_count_distinct_order_id
  sorts:
    - descending: true
      fieldId: dbt_orders_order_date_month
    - descending: true
      fieldId: dbt_orders_count_distinct_order_id
  tableCalculations: []
name: How many orders do gmail customers make compared to all others?
pivotConfig:
  columns:
    - is_gmail_email
slug: how-many-orders-do-gmail-customers-make-compared-to-all-others
spaceSlug: "-sales"
tableConfig:
  columnOrder:
    - Profit Binned
    - dbt_orders_order_date_month
    - is_gmail_email
    - dbt_orders_count_distinct_order_id
tableName: dbt_orders
verification: null
version: 1
