chartConfig:
  config:
    eChartsConfig:
      showAxisTicks: false
    layout: {}
  type: cartesian
contentType: chart
dashboardSlug: a-bunch-of-markdown-and-big-values
description: >-
  This visualization displays the frequency of orders grouped by custom date
  periods, revealing temporal patterns and trends in order volume across your
  specified timeframe.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - dbt_orders_order_date_custom_period
  exploreName: dbt_orders
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics: []
  sorts:
    - descending: false
      fieldId: dbt_orders_order_date_custom_period
  tableCalculations: []
name: How are orders distributed across custom time periods?
parameters:
  dbt_orders.custom_range_end: "2025-12-10"
  dbt_orders.custom_range_start: "2025-12-01"
slug: how-are-orders-distributed-across-custom-time-periods
spaceSlug: "-sales"
tableConfig:
  columnOrder:
    - dbt_orders_order_date_custom_period
tableName: dbt_orders
verification: null
version: 1
