chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: dbt_orders_currency
            yRef:
              field: dbt_orders_email
          isFilteredOut: false
          type: bar
          yAxisIndex: 0
      showAxisTicks: false
    layout:
      xField: dbt_orders_currency
      yField:
        - dbt_orders_email
  type: cartesian
contentType: chart
description: >-
  Displays the count of orders grouped by customer email address and currency,
  revealing which customers are ordering in different currencies and their order
  frequency.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_order_id
    - dbt_orders_email
    - dbt_orders_browser
    - dbt_orders_currency
    - dbt_orders_basket_total
    - dbt_orders_partner_commission
    - dbt_orders_partner_id
    - dbt_orders_partner_name
    - dbt_orders_profit
    - dbt_orders_referrer
    - dbt_orders_shipping_city
    - dbt_orders_shipping_country
    - dbt_orders_order_date_hour
  exploreName: dbt_orders
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics: []
  sorts:
    - descending: false
      fieldId: dbt_orders_currency
  tableCalculations: []
name: How many orders were placed by each email address across different currencies?
slug: how-many-orders-were-placed-by-each-email-address-across-different-currencies
spaceSlug: testing
tableConfig:
  columnOrder:
    - dbt_orders_order_id
    - dbt_orders_email
    - dbt_orders_browser
    - dbt_orders_currency
    - dbt_orders_basket_total
    - dbt_orders_partner_commission
    - dbt_orders_partner_id
    - dbt_orders_partner_name
    - dbt_orders_profit
    - dbt_orders_referrer
    - dbt_orders_shipping_city
    - dbt_orders_shipping_country
    - dbt_orders_order_date_hour
tableName: dbt_orders
verification: null
version: 1
