chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      series:
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_basket_total
          smooth: true
          type: line
          yAxisIndex: 0
      xAxis:
        - name: Month
      yAxis:
        - name: Revenue
    layout:
      showGridY: true
      xField: dbt_orders_order_date_month
      yField:
        - dbt_orders_sum_of_basket_total
  type: cartesian
contentType: chart
description: null
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_order_date_month
  exploreName: dbt_orders
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_sum_of_basket_total
  sorts:
    - descending: false
      fieldId: dbt_orders_order_date_month
  tableCalculations: []
name: KPI - Monthly Revenue Trend
slug: kpi-monthly-revenue-trend
spaceSlug: shared
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_sum_of_basket_total
tableName: dbt_orders
verification: null
version: 1
