chartConfig:
  config:
    label: Unique Customers
    selectedField: dbt_orders_count_distinct_user_id
    showBigNumberLabel: true
  type: big_number
contentType: chart
description: null
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions: []
  exploreName: dbt_orders
  filters: {}
  limit: 1
  metricOverrides: {}
  metrics:
    - dbt_orders_count_distinct_user_id
  sorts: []
  tableCalculations: []
name: Unique Customers
slug: kpi-unique-customers
spaceSlug: kpi-metrics
tableConfig:
  columnOrder:
    - dbt_orders_count_distinct_user_id
tableName: dbt_orders
verification: null
version: 1
