chartConfig:
  config:
    label: Total Orders
    selectedField: dbt_orders_total_orders
    showBigNumberLabel: true
  type: big_number
contentType: chart
description: null
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions: []
  exploreName: dbt_orders
  filters: {}
  limit: 1
  metricOverrides: {}
  metrics:
    - dbt_orders_total_orders
  sorts: []
  tableCalculations: []
name: Total Orders
slug: kpi-total-orders
spaceSlug: kpi-metrics
tableConfig:
  columnOrder:
    - dbt_orders_total_orders
tableName: dbt_orders
verification: null
version: 1
