chartConfig:
  config:
    comparisonFormat: raw
    flipColors: false
    label: Avg Order Value
    selectedField: dbt_orders_average_of_basket_total
    showBigNumberLabel: true
    showComparison: false
  type: big_number
contentType: chart
description: null
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions: []
  exploreName: dbt_orders
  filters: {}
  limit: 1
  metricOverrides: {}
  metrics:
    - dbt_orders_average_of_basket_total
  sorts: []
  tableCalculations: []
name: KPI - Avg Order Value
slug: kpi-avg-order-value-big-number
spaceSlug: shared
tableConfig:
  columnOrder:
    - dbt_orders_average_of_basket_total
tableName: dbt_orders
verification: null
version: 1
