chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: true
        type: plain
      series:
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_basket_total
          name: Sum of basket total
          type: line
          yAxisIndex: 0
      xAxis:
        - name: Order Month
      yAxis:
        - name: Total Revenue
    layout:
      xField: dbt_orders_order_date_month
      yField:
        - dbt_orders_sum_of_basket_total
  type: cartesian
contentType: chart
dashboardSlug: redwood-ranch-partner-performance-dashboard
description: >-
  Total revenue from Redwood Ranch by month. Shows how revenue is trending over
  time for this partner.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - dbt_orders_order_date_month
  exploreName: dbt_orders
  filters:
    dimensions:
      and:
        - id: 24e5e7de-b522-4866-b96a-4935db15558f
          operator: equals
          target:
            fieldId: dbt_orders_partner_name
          values:
            - Redwood Ranch
      id: da4a65f1-f00c-48bc-bca0-afdfc77ec9b2
    metrics:
      and: []
      id: ee42234f-086f-4ef5-847d-c2014cad5e67
  limit: 36
  metricOverrides: {}
  metrics:
    - dbt_orders_sum_of_basket_total
  sorts:
    - descending: false
      fieldId: dbt_orders_order_date_month
  tableCalculations: []
name: Monthly Revenue Trend (Redwood Ranch)
slug: monthly-revenue-trend-redwood-ranch
spaceSlug: sql-runner-space
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_sum_of_basket_total
tableName: dbt_orders
verification: null
version: 1
