chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: true
        type: plain
      series:
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_count_distinct_order_id
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Happy Harvesters
          stack: dbt_orders_count_distinct_order_id
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_count_distinct_order_id
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Redwood Ranch
          stack: dbt_orders_count_distinct_order_id
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_count_distinct_order_id
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Peat, Fruits and Leaves
          stack: dbt_orders_count_distinct_order_id
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_count_distinct_order_id
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Trowels R Us
          stack: dbt_orders_count_distinct_order_id
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_count_distinct_order_id
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Plant Paradise
          stack: dbt_orders_count_distinct_order_id
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_count_distinct_order_id
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Sprout Society
          stack: dbt_orders_count_distinct_order_id
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_count_distinct_order_id
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Garden of Sweden
          stack: dbt_orders_count_distinct_order_id
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_count_distinct_order_id
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Roots & Shoots
          stack: dbt_orders_count_distinct_order_id
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_count_distinct_order_id
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Potted Paradise
          stack: dbt_orders_count_distinct_order_id
          type: bar
          yAxisIndex: 0
      title:
        text: >-
          Monthly Order Counts by Partner (Redwood Ranch Highlighted) - Last
          Year
      xAxis:
        - name: Order Month
          type: time
      yAxis:
        - name: Order Count
          type: value
    layout:
      xField: dbt_orders_order_date_month
      yField:
        - dbt_orders_count_distinct_order_id
  type: cartesian
contentType: chart
dashboardSlug: sales-redwood-ranch
description: >-
  This stacked bar chart compares the number of orders placed each month last
  year by Redwood Ranch versus other partners. Each bar represents a month, and
  the segments show order counts for each partner.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_order_date_month
    - dbt_orders_partner_name
  exploreName: dbt_orders
  filters:
    dimensions:
      and:
        - id: 57b00232-3d39-41f3-b26a-ef79befc9b99
          operator: equals
          target:
            fieldFilterType: date
            fieldId: dbt_orders_order_date_year
          values:
            - "2024-01-01"
      id: d2c53bea-29de-460a-be39-9ff1be6f1c47
    metrics:
      and: []
      id: de7e443a-bf22-4a65-98ed-615e810654cc
  limit: 100
  metricOverrides: {}
  metrics:
    - dbt_orders_count_distinct_order_id
  sorts:
    - descending: false
      fieldId: dbt_orders_order_date_month
  tableCalculations: []
name: Monthly Order Counts by Partner (Redwood Ranch Highlighted) - Last Year
slug: monthly-order-counts-by-partner-redwood-ranch-highlighted-last-year
spaceSlug: "-sales"
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_partner_name
    - dbt_orders_count_distinct_order_id
tableName: dbt_orders
verification: null
version: 1
