chartConfig:
  config:
    eChartsConfig:
      series:
        - color: "#7262FF"
          encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_count_distinct_order_id
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Redwood Ranch
          stack: dbt_orders_count_distinct_order_id
          type: bar
          yAxisIndex: 0
        - color: "#D7C1FA"
          encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_count_distinct_order_id
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Peat, Fruits and Leaves
          stack: dbt_orders_count_distinct_order_id
          type: bar
          yAxisIndex: 0
        - color: "#98F4D1"
          encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_count_distinct_order_id
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Trowels R Us
          stack: dbt_orders_count_distinct_order_id
          type: bar
          yAxisIndex: 0
        - color: "#000000"
          encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_count_distinct_order_id
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Plant Paradise
          stack: dbt_orders_count_distinct_order_id
          type: bar
          yAxisIndex: 0
        - color: "#fc8452"
          encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_count_distinct_order_id
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Garden of Sweden
          stack: dbt_orders_count_distinct_order_id
          type: bar
          yAxisIndex: 0
    layout:
      xField: dbt_orders_order_date_month
      yField:
        - dbt_orders_count_distinct_order_id
    metadata:
      dbt_orders_count_distinct_order_id.Garden of Sweden:
        color: "#fc8452"
      dbt_orders_count_distinct_order_id.Peat, Fruits and Leaves:
        color: "#D7C1FA"
      dbt_orders_count_distinct_order_id.Plant Paradise:
        color: "#000000"
      dbt_orders_count_distinct_order_id.Redwood Ranch:
        color: "#7262FF"
      dbt_orders_count_distinct_order_id.Trowels R Us:
        color: "#98F4D1"
  type: cartesian
contentType: chart
description: null
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_partner_name
    - dbt_orders_order_date_month
  exploreName: dbt_orders
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_count_distinct_order_id
  sorts:
    - descending: true
      fieldId: dbt_orders_count_distinct_order_id
  tableCalculations: []
name: Monthly orders by partner
pivotConfig:
  columns:
    - dbt_orders_partner_name
slug: monthly-orders-by-partner
spaceSlug: "-sales"
tableConfig:
  columnOrder:
    - dbt_orders_partner_name
    - dbt_orders_order_date_month
    - dbt_orders_count_distinct_order_id
tableName: dbt_orders
verification: null
version: 1
