chartConfig:
  config:
    spec:
      config:
        axis:
          grid: false
        view:
          stroke: transparent
      encoding:
        color:
          field: dbt_baskets_product_name
          legend: null
          type: nominal
        size:
          field: dbt_baskets_count_of_product_name
          title: Count of Product Name
          type: quantitative
        text:
          field: dbt_baskets_product_name
          type: nominal
        tooltip:
          - field: dbt_baskets_product_name
            title: Product Name
            type: nominal
          - field: dbt_baskets_count_of_product_name
            title: Count
            type: quantitative
        x:
          axis: null
          field: x
          type: quantitative
        "y":
          axis: null
          field: "y"
          type: quantitative
      mark:
        tooltip: true
        type: text
      transform:
        - window:
            - as: rank
              op: rank
        - as: "y"
          calculate: datum.rank * 3
        - as: x
          calculate: random() * 3
  type: custom
contentType: chart
dashboardSlug: "-kpi-dashboard"
description: ""
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - dbt_baskets_product_name
  exploreName: dbt_baskets
  filters: {}
  limit: 20
  metricOverrides: {}
  metrics:
    - dbt_baskets_count_of_product_name
  sorts:
    - descending: false
      fieldId: dbt_baskets_product_name
  tableCalculations: []
name: Most popular product categories
slug: most-popular-product-categories
spaceSlug: "-key-company-dashboards"
tableConfig:
  columnOrder:
    - dbt_baskets_product_name
    - dbt_baskets_count_of_product_name
tableName: dbt_baskets
verification: null
version: 1
