chartConfig:
  config:
    eChartsConfig:
      series:
        - color: "#7CA982"
          encode:
            xRef:
              field: dbt_users_created_date_month
            yRef:
              field: dbt_users_count_distinct_of_user_id
          type: bar
      xAxis:
        - name: Month
          type: category
      yAxis:
        - name: New Customers
    layout:
      xField: dbt_users_created_date_month
      yField:
        - dbt_users_count_distinct_of_user_id
  type: cartesian
contentType: chart
description: >-
  Track customer acquisition trends by showing the number of new customer
  signups each month. Helps identify growth patterns and marketing
  effectiveness.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_users_created_date_month
  exploreName: dbt_users
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_users_count_distinct_of_user_id
  sorts:
    - descending: false
      fieldId: dbt_users_created_date_month
  tableCalculations: []
name: New Customers by Month
slug: new-customers-by-month
spaceSlug: "-sales"
tableConfig:
  columnOrder:
    - dbt_users_created_date_month
    - dbt_users_count_distinct_of_user_id
tableName: dbt_users
verification: null
version: 1
