chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: dbt_orders_partner_name
            yRef:
              field: dbt_orders_count_distinct_order_id
          isFilteredOut: false
          type: bar
          yAxisIndex: 0
      showAxisTicks: false
    layout:
      xField: dbt_orders_partner_name
      yField:
        - dbt_orders_count_distinct_order_id
  type: cartesian
contentType: chart
description: ""
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_partner_name
  exploreName: dbt_orders
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_count_distinct_order_id
  sorts:
    - descending: false
      fieldId: dbt_orders_partner_name
  tableCalculations: []
name: New Google Sheet data
slug: new-google-sheet-data
spaceSlug: shared
tableConfig:
  columnOrder:
    - dbt_orders_partner_name
    - dbt_orders_count_distinct_order_id
tableName: dbt_orders
verification: null
version: 1
