chartConfig:
  config:
    columns: {}
    conditionalFormattings: []
    hideRowNumbers: false
    metricsAsRows: false
    showColumnCalculation: false
    showResultsTotal: false
    showRowCalculation: false
    showSubtotals: false
    showTableNames: true
  type: table
contentType: chart
description: ""
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_users_browser
    - dbt_users_email
  exploreName: dbt_users
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_count_distinct_order_id
  sorts:
    - descending: true
      fieldId: dbt_orders_count_distinct_order_id
  tableCalculations: []
name: Non Pivoted
slug: non-pivoted-1761821818352
spaceSlug: bruno-s-space
tableConfig:
  columnOrder:
    - dbt_users_browser
    - dbt_users_email
    - dbt_orders_count_distinct_order_id
tableName: dbt_users
verification: null
version: 1
