chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: true
        type: scroll
      series:
        - encode:
            xRef:
              field: dbt_orders_referrer
            yRef:
              field: dbt_orders_count_distinct_order_id
          isFilteredOut: false
          name: Order count
          type: bar
          yAxisIndex: 0
      xAxis:
        - name: Referrer
      yAxis:
        - name: Order Count
    layout:
      stack: false
      xField: dbt_orders_referrer
      yField:
        - dbt_orders_count_distinct_order_id
  type: cartesian
contentType: chart
dashboardSlug: sales-kpi-dashboard
description: Bar chart showing order count by referrer to analyze traffic sources.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_referrer
  exploreName: dbt_orders
  filters:
    dimensions:
      and: []
      id: 1bea002f-bc0d-408c-ac05-661c9152e48e
    metrics:
      and: []
      id: e4556a79-7687-4fbf-8457-b69bfa175291
    tableCalculations:
      and: []
      id: c732b95e-879b-42d3-a533-0d4366fd1343
  limit: 10
  metricOverrides: {}
  metrics:
    - dbt_orders_count_distinct_order_id
  sorts:
    - descending: true
      fieldId: dbt_orders_count_distinct_order_id
  tableCalculations: []
name: Orders by Referrer
slug: orders-by-referrer
spaceSlug: shared/apollo
tableConfig:
  columnOrder:
    - dbt_orders_referrer
    - dbt_orders_count_distinct_order_id
tableName: dbt_orders
verification: null
version: 1
