chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: true
        type: scroll
      series:
        - encode:
            xRef:
              field: monthly_partner_info_partner_size
            yRef:
              field: monthly_partner_info_total_orders
          isFilteredOut: false
          name: Total Orders
          type: bar
          yAxisIndex: 0
      showAxisTicks: false
      xAxis:
        - name: Partner Size
      yAxis:
        - name: Total Orders
    layout:
      flipAxes: true
      xField: monthly_partner_info_partner_size
      yField:
        - monthly_partner_info_total_orders
  type: cartesian
contentType: chart
dashboardSlug: partner-performance-dashboard
description: Analyze how partner size correlates with order volume and revenue.
metricQuery:
  additionalMetrics:
    - baseDimensionName: dbt_orders_sum_basket_total
      description: Sum of basket totals across all orders for each partner size.
      label: Total Revenue
      name: total_revenue
      sql: "`dbt_orders_sum_of_basket_total`"
      table: monthly_partner_info
      type: sum
      uuid: 1b741391-6962-430f-8464-684dc0526298
    - baseDimensionName: dbt_orders_count_distinct_order_id
      description: Count of distinct order IDs for each partner size.
      label: Total Orders
      name: total_orders
      sql: "`dbt_orders_count_distinct_order_id`"
      table: monthly_partner_info
      type: sum
      uuid: dee3cd43-55c2-4966-a89c-726426deadd5
  customDimensions: []
  dimensions:
    - monthly_partner_info_partner_size
  exploreName: monthly_partner_info
  filters:
    dimensions:
      and: []
      id: a638d55d-dcd5-4419-8168-6c38942ae79b
    metrics:
      and: []
      id: a79597be-c3e2-49e9-a27d-4a5a1378b08a
    tableCalculations:
      and: []
      id: 03bd23e8-0ac1-4fee-98f3-8fce8da4487a
  limit: 1000
  metricOverrides: {}
  metrics:
    - monthly_partner_info_total_orders
    - monthly_partner_info_total_revenue
  sorts:
    - descending: false
      fieldId: monthly_partner_info_partner_size
  tableCalculations: []
name: Orders and Revenue by Partner Size
slug: orders-and-revenue-by-partner-size
spaceSlug: shared/apollo
tableConfig:
  columnOrder:
    - monthly_partner_info_partner_size
    - monthly_partner_info_total_orders
    - monthly_partner_info_total_revenue
tableName: monthly_partner_info
verification: null
version: 1
