chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: true
        type: scroll
      series:
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_count_distinct_order_id
          isFilteredOut: false
          name: Order count
          type: bar
          yAxisIndex: 0
      xAxis:
        - name: Month
      yAxis:
        - name: Order Count
    layout:
      stack: false
      xField: dbt_orders_order_date_month
      yField:
        - dbt_orders_count_distinct_order_id
  type: cartesian
contentType: chart
dashboardSlug: sales-kpi-dashboard
description: Monthly trend of order count to track sales activity and volume.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_order_date_month
  exploreName: dbt_orders
  filters:
    dimensions:
      and: []
      id: 82628cfa-d68d-4e2a-852e-8fc91efc0c29
    metrics:
      and: []
      id: 0716932e-f37c-4ca1-b5ae-2b750c08e01c
    tableCalculations:
      and: []
      id: 353c7af5-1836-4906-8ad9-92d6e6f89bcf
  limit: 1000
  metricOverrides: {}
  metrics:
    - dbt_orders_count_distinct_order_id
  sorts:
    - descending: false
      fieldId: dbt_orders_order_date_month
  tableCalculations: []
name: Order Volume Trend Over Time
slug: order-volume-trend-over-time
spaceSlug: shared/apollo
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_count_distinct_order_id
tableName: dbt_orders
verification: null
version: 1
