chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: dbt_orders_browser
            yRef:
              field: dbt_orders_count_distinct_order_id
          isFilteredOut: false
          type: bar
          yAxisIndex: 0
    layout:
      xField: dbt_orders_browser
      yField:
        - dbt_orders_count_distinct_order_id
  type: cartesian
contentType: chart
dashboardSlug: "-kpi-dashboard"
description: ""
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - dbt_orders_browser
  exploreName: dbt_orders
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_count_distinct_order_id
  sorts:
    - descending: true
      fieldId: dbt_orders_count_distinct_order_id
  tableCalculations: []
name: order counts
slug: order-counts
spaceSlug: "-key-company-dashboards"
tableConfig:
  columnOrder:
    - dbt_orders_browser
    - dbt_orders_count_distinct_order_id
tableName: dbt_orders
verification: null
version: 1
