chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: true
        type: plain
      series:
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_count_distinct_order_id
          name: Order count
          type: line
          yAxisIndex: 0
      xAxis:
        - name: Order Month
      yAxis:
        - name: Order Count
    layout:
      xField: dbt_orders_order_date_month
      yField:
        - dbt_orders_count_distinct_order_id
  type: cartesian
contentType: chart
dashboardSlug: redwood-ranch-partner-performance-dashboard
description: Number of orders placed by Redwood Ranch each month.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_order_date_month
  exploreName: dbt_orders
  filters:
    dimensions:
      and:
        - id: f59aaff9-b407-4514-afdf-de41253cc497
          operator: equals
          target:
            fieldId: dbt_orders_partner_name
          values:
            - Redwood Ranch
      id: dcf3c27d-e276-4943-a7af-a4fa9c7df953
    metrics:
      and: []
      id: 336fa915-65ba-47b3-9405-a3e19ddfa750
  limit: 36
  metricOverrides: {}
  metrics:
    - dbt_orders_count_distinct_order_id
  sorts:
    - descending: false
      fieldId: dbt_orders_order_date_month
  tableCalculations: []
name: Order Volume by Month (Redwood Ranch)
slug: order-volume-by-month-redwood-ranch
spaceSlug: sql-runner-space
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_count_distinct_order_id
tableName: dbt_orders
verification: null
version: 1
