chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: true
        type: scroll
      series:
        - encode:
            xRef:
              field: dbt_orders_shipping_country
            yRef:
              field: dbt_orders_count_distinct_order_id
          isFilteredOut: false
          name: Order count
          type: bar
          yAxisIndex: 0
      xAxis:
        - name: Shipping Country
      yAxis:
        - name: Order Count
    layout:
      flipAxes: true
      xField: dbt_orders_shipping_country
      yField:
        - dbt_orders_count_distinct_order_id
  type: cartesian
contentType: chart
dashboardSlug: orders-support-team-dashboard
description: >-
  Horizontal bar chart showing order counts by shipping country for the last 6
  months.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_shipping_country
  exploreName: dbt_orders
  filters:
    dimensions:
      and:
        - id: c84fa132-6809-4806-845d-297423cf2d7d
          operator: inThePast
          settings:
            completed: true
            unitOfTime: months
          target:
            fieldId: dbt_orders_order_date_month
          values:
            - 6
      id: 0f3ce05c-d87e-4e27-bf1e-0b42c6b78595
    metrics:
      and: []
      id: 9631aa50-16d2-4081-85cb-6c98aed93d18
    tableCalculations:
      and: []
      id: 6fe16294-27ce-499a-bc6b-3d432b7376f8
  limit: 20
  metricOverrides: {}
  metrics:
    - dbt_orders_count_distinct_order_id
  sorts:
    - descending: true
      fieldId: dbt_orders_count_distinct_order_id
  tableCalculations: []
name: Orders by Shipping Country (Last 6 Months)
slug: orders-by-shipping-country-last-6-months
spaceSlug: shared
tableConfig:
  columnOrder:
    - dbt_orders_shipping_country
    - dbt_orders_count_distinct_order_id
tableName: dbt_orders
verification: null
version: 1
