chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: true
        type: plain
      series:
        - encode:
            xRef:
              field: dbt_orders_shipping_country
            yRef:
              field: dbt_orders_count_distinct_order_id
          name: Order count
          type: bar
          yAxisIndex: 0
      title:
        text: Orders by Country
      xAxis:
        - name: Country
          type: category
      yAxis:
        - name: Order Count
          type: value
    layout:
      xField: dbt_orders_shipping_country
      yField:
        - dbt_orders_count_distinct_order_id
  type: cartesian
contentType: chart
dashboardSlug: business-pulse-revenue-customers-support-overview
description: See which countries are driving the most orders.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_shipping_country
  exploreName: dbt_orders
  filters:
    dimensions:
      and: []
      id: bc23f8ad-faad-4c16-b369-569d6135bd5b
    metrics:
      and: []
      id: c9c47df6-c679-4abf-a599-d402823e4059
  limit: 10
  metricOverrides: {}
  metrics:
    - dbt_orders_count_distinct_order_id
  sorts:
    - descending: true
      fieldId: dbt_orders_count_distinct_order_id
  tableCalculations: []
name: Orders by Country
slug: orders-by-country-1
spaceSlug: ai-agent-generated
tableConfig:
  columnOrder:
    - dbt_orders_shipping_country
    - dbt_orders_count_distinct_order_id
tableName: dbt_orders
verification: null
version: 1
