chartConfig:
  config:
    eChartsConfig:
      series:
        - color: "#7162FF"
          encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_profit
          isFilteredOut: false
          label:
            position: top
            show: true
          type: bar
          yAxisIndex: 0
        - areaStyle: {}
          color: "#D4F7E9"
          encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: running_total_of_sum_of_profit
          isFilteredOut: false
          label:
            position: bottom
            show: true
          type: line
          yAxisIndex: 1
      xAxis:
        - name: Order Month
      yAxis:
        - name: ""
        - name: ""
    layout:
      xField: dbt_orders_order_date_month
      yField:
        - running_total_of_sum_of_profit
        - dbt_orders_sum_of_profit
  type: cartesian
contentType: chart
description: null
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - dbt_orders_order_date_month
  exploreName: dbt_orders
  filters: {}
  limit: 500
  metricOverrides:
    dbt_orders_sum_of_profit:
      formatOptions:
        compact: thousands
        currency: USD
        round: 0
        separator: default
        type: currency
  metrics:
    - dbt_orders_average_of_basket_total
    - dbt_orders_sum_of_profit
  sorts:
    - descending: true
      fieldId: dbt_orders_order_date_month
  tableCalculations:
    - displayName: Running total of Sum of profit
      format:
        compact: millions
        currency: USD
        round: 2
        separator: default
        type: number
      name: running_total_of_sum_of_profit
      sql: >
        SUM(${dbt_orders.sum_of_profit}) OVER(ORDER BY
        `dbt_orders_order_date_month`   ROWS BETWEEN UNBOUNDED PRECEDING AND
        CURRENT ROW)
      type: number
name: Our example chart
slug: our-example-chrat
spaceSlug: shared
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_average_of_basket_total
    - dbt_orders_sum_of_profit
    - running_total_of_sum_of_profit
tableName: dbt_orders
verification: null
version: 1
