chartConfig:
  config:
    columns: {}
    conditionalFormattings: []
    hideRowNumbers: false
    metricsAsRows: false
    showColumnCalculation: false
    showResultsTotal: false
    showRowCalculation: false
    showSubtotals: false
    showTableNames: true
  type: table
contentType: chart
dashboardSlug: order-revenue-dashboard
description: >-
  Detailed partner comparison table to spot high-revenue vs high-efficiency
  partners.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_partner_name
  exploreName: dbt_orders
  filters:
    dimensions:
      and: []
      id: f4f19cbd-dad6-4d8e-a604-749865bec6d1
    metrics:
      and: []
      id: 96d0db61-9707-4545-abf5-9ec6fed3940a
    tableCalculations:
      and: []
      id: 093eb318-c6eb-4d53-8d46-808f476d9f88
  limit: 1000
  metricOverrides: {}
  metrics:
    - dbt_orders_sum_of_basket_total
    - dbt_orders_count_distinct_order_id
    - dbt_orders_average_of_basket_total
    - dbt_orders_sum_of_profit
  sorts:
    - descending: true
      fieldId: dbt_orders_sum_of_basket_total
  tableCalculations: []
name: Partner performance table (Revenue, Orders, AOV, Profit)
slug: partner-performance-table-revenue-orders-aov-profit
spaceSlug: shared
tableConfig:
  columnOrder:
    - dbt_orders_partner_name
    - dbt_orders_sum_of_basket_total
    - dbt_orders_count_distinct_order_id
    - dbt_orders_average_of_basket_total
    - dbt_orders_sum_of_profit
tableName: dbt_orders
verification: null
version: 1
