chartConfig:
  config:
    groupColorOverrides: {}
    groupFieldIds:
      - monthly_partner_info_dbt_orders_partner_name
    groupLabelOverrides:
      Roots & Shoots: Roots
      Trowels R Us: Trowels
    groupSortOverrides: []
    groupValueOptionOverrides: {}
    isDonut: true
    legendMaxItemLength: 30
    legendPosition: horizontal
    metricId: monthly_partner_info_num_sum_of_num
    showLegend: true
    showPercentage: true
    showValue: false
    valueLabel: outside
  type: pie
contentType: chart
description: ""
metricQuery:
  additionalMetrics:
    - baseDimensionName: partner_size
      description: "Sum of Num on the table Partner orders "
      formatOptions:
        separator: default
        type: default
      label: Sum of Num
      name: num_sum_of_num
      sql: "`num`"
      table: monthly_partner_info
      type: sum
      uuid: b984a571-78b3-462e-a194-90c704418425
  customDimensions: []
  dimensions:
    - monthly_partner_info_dbt_orders_partner_name
  exploreName: monthly_partner_info
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - monthly_partner_info_num_sum_of_num
  sorts:
    - descending: false
      fieldId: monthly_partner_info_dbt_orders_partner_name
  tableCalculations: []
name: Partner orders pie
slug: partner-orders-pie
spaceSlug: shared
tableConfig:
  columnOrder:
    - monthly_partner_info_dbt_orders_partner_name
    - monthly_partner_info_num_sum_of_num
tableName: monthly_partner_info
verification: null
version: 1
