chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: true
        type: scroll
      series:
        - areaStyle: {}
          encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_profit
          isFilteredOut: false
          name: Sum of profit
          stack: total
          type: line
          yAxisIndex: 0
      xAxis:
        - name: Month
      yAxis:
        - name: Total Profit
    layout:
      xField: dbt_orders_order_date_month
      yField:
        - dbt_orders_sum_of_profit
  type: cartesian
contentType: chart
dashboardSlug: sales-kpi-dashboard
description: Monthly trend of total profit to monitor profitability.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_order_date_month
  exploreName: dbt_orders
  filters:
    dimensions:
      and: []
      id: dcb587f0-3518-49e7-a791-20c44b65ce52
    metrics:
      and: []
      id: 7aa5bc14-5673-453b-8c73-2940f1ff3c82
    tableCalculations:
      and: []
      id: 89d43394-1a1b-4dfa-83e3-94e7857ebdd6
  limit: 1000
  metricOverrides: {}
  metrics:
    - dbt_orders_sum_of_profit
  sorts:
    - descending: false
      fieldId: dbt_orders_order_date_month
  tableCalculations: []
name: Profit Trend Over Time
slug: profit-trend-over-time
spaceSlug: shared/apollo
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_sum_of_profit
tableName: dbt_orders
verification: null
version: 1
