chartConfig:
  config:
    spec:
      $schema: https://vega.github.io/schema/vega-lite/v5.json
      encoding:
        color:
          aggregate: sum
          field: dbt_orders_sum_of_profit
          type: quantitative
        x:
          axis:
            labelColor: "#6e7079"
            tickColor: "#6e7079"
          field: dbt_orders_order_date_quarter
          type: temporal
        "y":
          axis:
            labelColor: "#6e7079"
            tickColor: "#6e7079"
          field: dbt_orders_partner_name
          type: ordinal
      mark: rect
  type: custom
contentType: chart
description: null
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - dbt_orders_partner_name
    - dbt_orders_order_date_quarter
  exploreName: dbt_orders
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_sum_of_profit
  sorts:
    - descending: true
      fieldId: dbt_orders_order_date_quarter
  tableCalculations: []
name: Quarterly profit heatmap
slug: quarterly-profit-heatmap
spaceSlug: shared/custom-visuals
tableConfig:
  columnOrder:
    - dbt_orders_partner_name
    - dbt_orders_order_date_quarter
    - dbt_orders_sum_of_profit
tableName: dbt_orders
verification: null
version: 1
