chartConfig:
  config:
    label: Revenue
    selectedField: dbt_orders_sum_of_basket_total
    showBigNumberLabel: true
    style: K
  type: big_number
contentType: chart
description: null
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions: []
  exploreName: dbt_orders
  filters: {}
  limit: 1
  metricOverrides: {}
  metrics:
    - dbt_orders_sum_of_basket_total
  sorts: []
  tableCalculations: []
name: Redwood Ranch Revenue
slug: redwood-ranch-revenue
spaceSlug: redwood-ranch
tableConfig:
  columnOrder:
    - dbt_orders_sum_of_basket_total
tableName: dbt_orders
verification: null
version: 1
