chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: true
        type: scroll
      series:
        - encode:
            xRef:
              field: dbt_support_requests_reason
            yRef:
              field: dbt_support_requests_count_distinct_request_id
          isFilteredOut: false
          name: Total requests
          type: bar
          yAxisIndex: 0
      xAxis:
        - name: Reason
      yAxis:
        - name: Requests
    layout:
      stack: false
      xField: dbt_support_requests_reason
      yField:
        - dbt_support_requests_count_distinct_request_id
  type: cartesian
contentType: chart
dashboardSlug: customer-feedback-support-dashboard
description: Breakdown of support requests by reason.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - dbt_support_requests_reason
  exploreName: dbt_support_requests
  filters:
    dimensions:
      and: []
      id: db2793fb-d4a7-4d5b-bbde-b1a5c344f705
    metrics:
      and: []
      id: 9d002f9c-5f8d-4d1d-999d-cc00f615b4aa
    tableCalculations:
      and: []
      id: 43af0700-25b0-4e4c-a95d-966cd1e5196d
  limit: 10
  metricOverrides: {}
  metrics:
    - dbt_support_requests_count_distinct_request_id
  sorts:
    - descending: true
      fieldId: dbt_support_requests_count_distinct_request_id
  tableCalculations: []
name: Requests by Reason
slug: requests-by-reason
spaceSlug: "-key-company-dashboards"
tableConfig:
  columnOrder:
    - dbt_support_requests_reason
    - dbt_support_requests_count_distinct_request_id
tableName: dbt_support_requests
verification: null
version: 1
