chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: true
        type: scroll
      series:
        - encode:
            xRef:
              field: monthly_partner_info_dbt_orders_partner_name
            yRef:
              field: monthly_partner_info_total_revenue
          isFilteredOut: false
          name: Total Revenue
          type: bar
          yAxisIndex: 0
      showAxisTicks: false
      title:
        text: Revenue by partner (last 6 months)
      xAxis:
        - name: Partner
      yAxis:
        - name: Total revenue (last 6 months)
    layout:
      stack: false
      xField: monthly_partner_info_dbt_orders_partner_name
      yField:
        - monthly_partner_info_total_revenue
  type: cartesian
contentType: chart
dashboardSlug: "-kpi-dashboard"
description: Total revenue by partner, filtered to the last 6 months based on order month.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - monthly_partner_info_dbt_orders_partner_name
  exploreName: monthly_partner_info
  filters:
    dimensions:
      and:
        - id: 062ca210-be7e-4683-ad68-f4b60a427f68
          operator: inThePast
          settings:
            completed: true
            unitOfTime: months
          target:
            fieldFilterType: date
            fieldId: monthly_partner_info_dbt_orders_order_date_month
          values:
            - 6
      id: 22670aa6-a9f0-4d7c-a9c0-9c045aacf8a7
    metrics:
      and: []
      id: ed09321c-c67c-498c-9a88-2bb28e0e49de
    tableCalculations:
      and: []
      id: d2687861-9ae0-4e7e-8fc0-875a79c61e9b
  limit: 50
  metricOverrides: {}
  metrics:
    - monthly_partner_info_total_revenue
  sorts:
    - descending: true
      fieldId: monthly_partner_info_total_revenue
  tableCalculations: []
name: Revenue by partner (last 6 months)
slug: revenue-by-partner-last-6-months-2
spaceSlug: "-key-company-dashboards"
tableConfig:
  columnOrder:
    - monthly_partner_info_dbt_orders_partner_name
    - monthly_partner_info_total_revenue
tableName: monthly_partner_info
verification: null
version: 1
