chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: true
        type: scroll
      series:
        - areaStyle: {}
          encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_basket_total
          isFilteredOut: false
          name: Revenue
          stack: total
          type: line
          yAxisIndex: 0
      showAxisTicks: false
      xAxis:
        - name: Order Month
      yAxis:
        - name: Revenue
    layout:
      xField: dbt_orders_order_date_month
      yField:
        - dbt_orders_sum_of_basket_total
  type: cartesian
contentType: chart
dashboardSlug: order-revenue-dashboard
description: Monthly revenue trend to monitor growth and seasonality.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_order_date_month
  exploreName: dbt_orders
  filters:
    dimensions:
      and: []
      id: 64e227ee-3ad8-47a3-92f3-72dfe7ce4199
    metrics:
      and: []
      id: 8fc63aaa-ac25-4e67-ab51-f548362d83ce
    tableCalculations:
      and: []
      id: 33f53f4c-4a82-42b0-a8d1-6ce54ba41d7f
  limit: 1000
  metricOverrides: {}
  metrics:
    - dbt_orders_sum_of_basket_total
  sorts:
    - descending: false
      fieldId: dbt_orders_order_date_month
  tableCalculations: []
name: Revenue trend over time (monthly)
slug: revenue-trend-over-time-monthly-1
spaceSlug: shared
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_sum_of_basket_total
tableName: dbt_orders
verification: null
version: 1
