chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: true
        type: scroll
      series:
        - encode:
            xRef:
              field: monthly_partner_info_dbt_orders_partner_name
            yRef:
              field: monthly_partner_info_total_revenue
          isFilteredOut: false
          name: Total Revenue
          type: bar
          yAxisIndex: 0
      showAxisTicks: false
      title:
        text: Revenue by Partner (Last 6 Months)
      xAxis:
        - name: Partner
      yAxis:
        - name: Revenue
    layout:
      stack: false
      xField: monthly_partner_info_dbt_orders_partner_name
      yField:
        - monthly_partner_info_total_revenue
  type: cartesian
contentType: chart
dashboardSlug: "-kpi-dashboard"
description: Total revenue summed over the last 6 months, grouped by partner.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - monthly_partner_info_dbt_orders_partner_name
  exploreName: monthly_partner_info
  filters:
    dimensions:
      and:
        - id: 11188d7b-5321-45f5-a9e1-947fc0c55c0e
          operator: inThePast
          settings:
            completed: true
            unitOfTime: months
          target:
            fieldFilterType: date
            fieldId: monthly_partner_info_dbt_orders_order_date_month
          values:
            - 6
      id: 51c3cdc6-de6c-4417-8abf-9ec27699a0e6
    metrics:
      and: []
      id: 34ca9c69-f1fd-4b39-8a64-5003f015e064
    tableCalculations:
      and: []
      id: ffb62613-da3c-491a-b02d-db06817a17fb
  limit: 50
  metricOverrides: {}
  metrics:
    - monthly_partner_info_total_revenue
  sorts:
    - descending: true
      fieldId: monthly_partner_info_total_revenue
  tableCalculations: []
name: Revenue by Partner (Last 6 Months)
slug: revenue-by-partner-last-6-months-6
spaceSlug: "-key-company-dashboards"
tableConfig:
  columnOrder:
    - monthly_partner_info_dbt_orders_partner_name
    - monthly_partner_info_total_revenue
tableName: monthly_partner_info
verification: null
version: 1
