chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: true
        type: scroll
      series:
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_basket_total
          isFilteredOut: false
          name: Revenue
          type: line
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_profit
          isFilteredOut: false
          name: Profit
          type: line
          yAxisIndex: 1
      showAxisTicks: false
      xAxis:
        - name: Order month
      yAxis:
        - name: Revenue
        - name: Profit
    layout:
      xField: dbt_orders_order_date_month
      yField:
        - dbt_orders_sum_of_basket_total
        - dbt_orders_sum_of_profit
  type: cartesian
contentType: chart
dashboardSlug: sales-dashboard-test
description: >-
  Monthly trend comparing Revenue and Profit. Uses a secondary Y-axis for
  Profit.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_order_date_month
  exploreName: dbt_orders
  filters:
    dimensions:
      and: []
      id: 074b7673-2b1c-4baf-82b5-456ca30370bd
    metrics:
      and: []
      id: 81cbece9-1969-4558-aff3-f571b6110ab2
    tableCalculations:
      and: []
      id: d10a534d-746f-40a4-a69e-87117b1f672d
  limit: 1000
  metricOverrides: {}
  metrics:
    - dbt_orders_sum_of_basket_total
    - dbt_orders_sum_of_profit
  sorts:
    - descending: false
      fieldId: dbt_orders_order_date_month
  tableCalculations: []
name: Revenue vs Profit by Month
slug: revenue-vs-profit-by-month
spaceSlug: test-space
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_sum_of_basket_total
    - dbt_orders_sum_of_profit
tableName: dbt_orders
verification: null
version: 1
