chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: true
        type: scroll
      series:
        - encode:
            xRef:
              field: monthly_partner_info_dbt_orders_partner_name
            yRef:
              field: monthly_partner_info_total_revenue
          isFilteredOut: false
          name: Total Revenue
          type: bar
          yAxisIndex: 0
      showAxisTicks: false
      title:
        text: Revenue by partner (last 6 months)
      xAxis:
        - name: Partner
      yAxis:
        - name: Total revenue
    layout:
      stack: false
      xField: monthly_partner_info_dbt_orders_partner_name
      yField:
        - monthly_partner_info_total_revenue
  type: cartesian
contentType: chart
dashboardSlug: "-kpi-dashboard"
description: Total partner revenue summed over the last 6 months, grouped by partner.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - monthly_partner_info_dbt_orders_partner_name
  exploreName: monthly_partner_info
  filters:
    dimensions:
      and:
        - id: cc9ca10e-39b9-4a39-8322-b02904140510
          operator: inThePast
          settings:
            completed: true
            unitOfTime: months
          target:
            fieldFilterType: date
            fieldId: monthly_partner_info_dbt_orders_order_date_month
          values:
            - 6
      id: d63f246e-5f7a-4b54-8224-af44bfc1cf8a
    metrics:
      and: []
      id: 253da0f9-d955-491d-8827-f7dc631ffdb5
    tableCalculations:
      and: []
      id: a9d64b9c-b78a-4553-addf-e48b9989a00c
  limit: 500
  metricOverrides: {}
  metrics:
    - monthly_partner_info_total_revenue
  sorts:
    - descending: true
      fieldId: monthly_partner_info_total_revenue
  tableCalculations: []
name: Revenue by partner (last 6 months)
slug: revenue-by-partner-last-6-months-4
spaceSlug: "-key-company-dashboards"
tableConfig:
  columnOrder:
    - monthly_partner_info_dbt_orders_partner_name
    - monthly_partner_info_total_revenue
tableName: monthly_partner_info
verification: null
version: 1
