chartConfig:
  config:
    comparisonFormat: raw
    flipColors: false
    label: selected orders dimension
    selectedField: dbt_orders_selected_dim
    showBigNumberLabel: true
    showComparison: false
  type: big_number
contentType: chart
dashboardSlug: parameters-example-2
description: ""
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - dbt_orders_selected_dim
  exploreName: dbt_orders
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics: []
  sorts:
    - descending: false
      fieldId: dbt_orders_selected_dim
  tableCalculations: []
name: selected dimension
slug: selected-dimension-1762175399090
spaceSlug: "-marketing/lightdash-features"
tableConfig:
  columnOrder:
    - dbt_orders_selected_dim
tableName: dbt_orders
verification: null
version: 1
