chartConfig:
  config:
    comparisonFormat: raw
    flipColors: false
    selectedField: dbt_orders_partner_name
    showBigNumberLabel: false
    showComparison: false
  type: big_number
contentType: chart
dashboardSlug: sales-updates
description: ""
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_partner_name
  exploreName: dbt_orders
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics: []
  sorts:
    - descending: false
      fieldId: dbt_orders_partner_name
  tableCalculations: []
name: Show chosen partner name
slug: show-chosen-partner-name
spaceSlug: "-sales"
tableConfig:
  columnOrder:
    - dbt_orders_partner_name
tableName: dbt_orders
verification: null
version: 1
