chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: dbt_support_requests_feedback_rating
            yRef:
              field: dbt_support_requests_count_distinct_request_id
          isFilteredOut: false
          type: line
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_support_requests_feedback_rating
            yRef:
              field: dbt_orders_average_of_basket_total
          type: line
          yAxisIndex: 1
    layout:
      flipAxes: false
      xField: dbt_support_requests_feedback_rating
      yField:
        - dbt_support_requests_count_distinct_request_id
        - dbt_orders_average_of_basket_total
  type: cartesian
contentType: chart
dashboardSlug: sales-example
description: ""
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - dbt_support_requests_feedback_rating
  exploreName: dbt_support_requests
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_average_of_basket_total
    - dbt_support_requests_count_distinct_request_id
  sorts:
    - descending: false
      fieldId: dbt_support_requests_feedback_rating
  tableCalculations: []
name: sort order issue
slug: sort-order-issue
spaceSlug: "-sales"
tableConfig:
  columnOrder:
    - dbt_support_requests_feedback_rating
    - dbt_orders_average_of_basket_total
    - dbt_support_requests_count_distinct_request_id
tableName: dbt_support_requests
verification: null
version: 1
