chartKind: vertical_bar
config:
  display: {}
  fieldConfig:
    groupBy: []
    x:
      reference: partner_id
      type: category
    "y":
      - aggregation: sum
        reference: order_id
  metadata:
    version: 1
  type: vertical_bar
contentType: sql_chart
description: ""
limit: 500
name: SQL Chart
slug: sql-chart-1
spaceSlug: shared
sql: "SELECT * FROM `lightdash-analytics`.`lightdash_demo_gardening`.`orders` "
version: 1
