chartKind: vertical_bar
config:
  display: {}
  fieldConfig:
    groupBy: []
    sortBy:
      - direction: ASC
        reference: order_date
    x:
      reference: order_date
      type: time
    "y":
      - aggregation: sum
        reference: profit
  metadata:
    version: 1
  type: vertical_bar
contentType: sql_chart
description: ""
limit: 500
name: sqrl
slug: sqrl
spaceSlug: "-sales"
sql: "SELECT * FROM `lightdash-analytics`.`lightdash_demo_gardening`.`orders` "
version: 1
