chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: true
        type: scroll
      series:
        - areaStyle: {}
          encode:
            xRef:
              field: dbt_support_requests_created_date
            yRef:
              field: dbt_support_requests_count_distinct_request_id
          isFilteredOut: false
          name: Total requests
          stack: total
          type: line
          yAxisIndex: 0
      xAxis:
        - name: Created Date
      yAxis:
        - name: Support Requests
    layout:
      xField: dbt_support_requests_created_date
      yField:
        - dbt_support_requests_count_distinct_request_id
  type: cartesian
contentType: chart
dashboardSlug: customer-feedback-support-dashboard
description: Trend of support requests received over time (by month).
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - dbt_support_requests_created_date
  exploreName: dbt_support_requests
  filters:
    dimensions:
      and: []
      id: e669c2e8-3678-41eb-956a-14af39917876
    metrics:
      and: []
      id: dd9585c4-4278-43b7-b7a6-5dc4d43c499f
    tableCalculations:
      and: []
      id: d214e19e-f119-468d-8db1-aaf93250170b
  limit: 100
  metricOverrides: {}
  metrics:
    - dbt_support_requests_count_distinct_request_id
  sorts:
    - descending: false
      fieldId: dbt_support_requests_created_date
  tableCalculations: []
name: Support Requests Over Time
slug: support-requests-over-time
spaceSlug: "-key-company-dashboards"
tableConfig:
  columnOrder:
    - dbt_support_requests_created_date
    - dbt_support_requests_count_distinct_request_id
tableName: dbt_support_requests
verification: null
version: 1
