chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: true
        type: scroll
      series:
        - areaStyle: {}
          encode:
            xRef:
              field: dbt_orders_order_date_custom_period
            yRef:
              field: dbt_support_requests_count_distinct_request_id
          name: Support Tickets
          stack: total
          type: line
          yAxisIndex: 0
      xAxis:
        - name: Order Date Period
      yAxis:
        - name: Support Tickets
    layout:
      xField: dbt_orders_order_date_custom_period
      yField:
        - dbt_support_requests_count_distinct_request_id
  type: cartesian
contentType: chart
dashboardSlug: customer-success-dashboard
description: >-
  Monitor the trend in support ticket volume over time to spot spikes or
  improvements in customer issues.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_order_date_custom_period
  exploreName: dbt_support_requests
  filters:
    dimensions:
      and: []
      id: a197cd07-89c3-4f9c-8cef-f9864cb5956e
    metrics:
      and: []
      id: 80a179ed-43a3-4b77-8310-a4052d08073f
    tableCalculations:
      and: []
      id: 733b1729-5409-4849-bdfb-b9c7e592a36b
  limit: 1000
  metricOverrides: {}
  metrics:
    - dbt_support_requests_count_distinct_request_id
  sorts:
    - descending: false
      fieldId: dbt_orders_order_date_custom_period
  tableCalculations: []
name: Support Ticket Volume Trend
slug: support-ticket-volume-trend
spaceSlug: shared
tableConfig:
  columnOrder:
    - dbt_orders_order_date_custom_period
    - dbt_support_requests_count_distinct_request_id
tableName: dbt_support_requests
verification: null
version: 1
