chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: gmail_users
            yRef:
              field: dbt_orders_user_id_user_count
          isFilteredOut: false
          type: bar
          yAxisIndex: 0
    layout:
      xField: gmail_users
      yField:
        - dbt_orders_user_id_user_count
  type: cartesian
contentType: chart
description: ""
metricQuery:
  additionalMetrics:
    - baseDimensionName: user_id
      description: "Count distinct of Total Users on the table Orders "
      formatOptions:
        separator: default
        type: default
      label: User Count
      name: user_id_user_count
      sql: ${TABLE}.user_id
      table: dbt_orders
      type: count_distinct
      uuid: ee8ffcfb-0db5-474e-82e7-81d1de168437
  customDimensions:
    - dimensionType: string
      id: gmail_users
      name: is_gmail_user
      sql: case when ${dbt_orders.email} like '%@gmail%' then true else false end
      table: dbt_orders
      type: sql
  dimensions:
    - gmail_users
  exploreName: dbt_orders
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_user_id_user_count
  sorts: []
  tableCalculations:
    - displayName: All Users
      format:
        separator: default
        type: default
      name: all_users
      sql: "sum(${dbt_orders.user_id_user_count}) over() "
      type: number
name: "Table calcs "
slug: table-calcs
spaceSlug: shared
tableConfig:
  columnOrder:
    - gmail_users
    - dbt_orders_user_id_user_count
    - all_users
tableName: dbt_orders
verification: null
version: 1
