chartConfig:
  config:
    groupColorOverrides: {}
    groupFieldIds:
      - partner_orders_partner_name
    groupLabelOverrides:
      Roots & Shoots: Roots
      Trowels R Us: Trowels
    groupSortOverrides: []
    groupValueOptionOverrides: {}
    isDonut: true
    legendMaxItemLength: 30
    legendPosition: horizontal
    metricId: partner_orders_num_sum_of_num
    showLegend: true
    showPercentage: true
    showValue: false
    valueLabel: outside
  type: pie
contentType: chart
dashboardSlug: sales-example
description: ""
metricQuery:
  additionalMetrics:
    - baseDimensionName: num
      description: "Sum of Num on the table Partner orders "
      formatOptions:
        separator: default
        type: default
      label: Sum of Num
      name: num_sum_of_num
      sql: "`num`"
      table: partner_orders
      type: sum
      uuid: 9cdca7e2-df3b-4281-8b6a-bfaa828511ff
  customDimensions: []
  dimensions:
    - partner_orders_partner_name
  exploreName: partner_orders
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - partner_orders_num_sum_of_num
  sorts:
    - descending: false
      fieldId: partner_orders_partner_name
  tableCalculations: []
name: test
slug: test-11
spaceSlug: "-sales"
tableConfig:
  columnOrder:
    - partner_orders_partner_name
    - partner_orders_num_sum_of_num
tableName: partner_orders
verification: null
version: 1
