chartConfig:
  config:
    comparisonFormat: raw
    flipColors: false
    selectedField: dbt_orders_count_distinct_order_id
    showBigNumberLabel: true
    showComparison: false
  type: big_number
contentType: chart
dashboardSlug: my-dashboard
description: ""
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_partner_name
    - dbt_orders_order_date_year
  exploreName: dbt_orders
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_count_distinct_order_id
  sorts:
    - descending: true
      fieldId: dbt_orders_count_distinct_order_id
  tableCalculations: []
name: test dash
slug: test-dash
spaceSlug: "-sales"
tableConfig:
  columnOrder:
    - dbt_orders_partner_name
    - dbt_orders_order_date_year
    - dbt_orders_count_distinct_order_id
tableName: dbt_orders
verification: null
version: 1
