chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_profit
          isFilteredOut: false
          label:
            position: top
            show: true
          type: bar
          yAxisIndex: 0
    layout:
      xField: dbt_orders_order_date_month
      yField:
        - dbt_orders_sum_of_profit
  type: cartesian
contentType: chart
dashboardSlug: "-kpi-dashboard"
description: ""
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - dbt_orders_order_date_month
  exploreName: dbt_orders
  filters: {}
  limit: 500
  metricOverrides:
    dbt_orders_sum_of_profit:
      formatOptions:
        compact: thousands
        round: 0
        separator: default
        type: number
  metrics:
    - dbt_orders_sum_of_profit
  sorts:
    - descending: true
      fieldId: dbt_orders_sum_of_profit
  tableCalculations: []
name: testing
slug: testing-5
spaceSlug: "-key-company-dashboards"
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_sum_of_profit
tableName: dbt_orders
verification: null
version: 1
