chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: dbt_orders_browser
            yRef:
              field: dbt_orders_sum_of_basket_total
          isFilteredOut: false
          label:
            position: top
            show: true
          type: bar
          yAxisIndex: 0
      tooltip: ""
    layout:
      xField: dbt_orders_browser
      yField:
        - dbt_orders_sum_of_basket_total
  type: cartesian
contentType: chart
dashboardSlug: "-kpi-dashboard"
description: ""
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - dbt_orders_browser
  exploreName: dbt_orders
  filters: {}
  limit: 500
  metricOverrides:
    dbt_orders_sum_of_basket_total:
      formatOptions:
        compact: thousands
        round: 1
        separator: default
        type: number
  metrics:
    - dbt_orders_sum_of_basket_total
  sorts:
    - descending: false
      fieldId: dbt_orders_browser
  tableCalculations: []
name: test formatting
slug: test-formatting
spaceSlug: "-key-company-dashboards"
tableConfig:
  columnOrder:
    - dbt_orders_browser
    - dbt_orders_sum_of_basket_total
tableName: dbt_orders
verification: null
version: 1
