chartConfig:
  config:
    eChartsConfig: {}
    layout: {}
  type: cartesian
contentType: chart
dashboardSlug: dashboard-with-tabs-test-saving-to
description: ""
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - dbt_support_requests_profit
  exploreName: dbt_support_requests
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_support_requests_count_distinct_request_id
  sorts:
    - descending: false
      fieldId: dbt_support_requests_profit
  tableCalculations: []
name: testing saving directly
slug: testing-saving-directly
spaceSlug: "-sales"
tableConfig:
  columnOrder:
    - dbt_support_requests_profit
    - dbt_support_requests_count_distinct_request_id
tableName: dbt_support_requests
verification: null
version: 1
