chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: true
        type: scroll
      series:
        - encode:
            xRef:
              field: dbt_baskets_product_name
            yRef:
              field: dbt_baskets_sum_of_basket_total
          isFilteredOut: false
          name: Revenue
          type: bar
          yAxisIndex: 0
      showAxisTicks: false
      title:
        text: Top 5 products by revenue
      xAxis:
        - name: Product
      yAxis:
        - name: Revenue
    layout:
      stack: false
      xField: dbt_baskets_product_name
      yField:
        - dbt_baskets_sum_of_basket_total
  type: cartesian
contentType: chart
dashboardSlug: "-kpi-dashboard"
description: Ranks products by total revenue and returns the top 5 products.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_baskets_product_name
  exploreName: dbt_baskets
  filters:
    dimensions:
      and: []
      id: 56248cdc-92dd-4eee-a6eb-de72751f66f1
    metrics:
      and: []
      id: bed86f6b-988c-45b3-8c28-2efd47288699
    tableCalculations:
      and: []
      id: 5d3f70a3-a016-4386-a6ad-b5f139965cae
  limit: 5
  metricOverrides: {}
  metrics:
    - dbt_baskets_sum_of_basket_total
  sorts:
    - descending: true
      fieldId: dbt_baskets_sum_of_basket_total
  tableCalculations: []
name: Top 5 products by revenue
slug: top-5-products-by-revenue
spaceSlug: "-key-company-dashboards"
tableConfig:
  columnOrder:
    - dbt_baskets_product_name
    - dbt_baskets_sum_of_basket_total
tableName: dbt_baskets
verification: null
version: 1
