chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: true
        type: scroll
      series:
        - encode:
            xRef:
              field: dbt_orders_partner_name
            yRef:
              field: dbt_orders_sum_of_basket_total
          isFilteredOut: false
          name: Revenue
          type: bar
          yAxisIndex: 0
      showAxisTicks: false
      xAxis:
        - name: Partner
      yAxis:
        - name: Revenue
    layout:
      flipAxes: true
      xField: dbt_orders_partner_name
      yField:
        - dbt_orders_sum_of_basket_total
  type: cartesian
contentType: chart
dashboardSlug: sales-dashboard-test
description: Ranks partners by total Revenue (top 10).
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_partner_name
  exploreName: dbt_orders
  filters:
    dimensions:
      and: []
      id: e8dc04fd-a8f0-42a1-a993-e9b4d157253e
    metrics:
      and: []
      id: 1cd6e9dd-f2d7-497d-a27f-6621e8640f0f
    tableCalculations:
      and: []
      id: ca3b56cf-8ec7-4098-9499-5ac9e1cf0f4b
  limit: 10
  metricOverrides: {}
  metrics:
    - dbt_orders_sum_of_basket_total
  sorts:
    - descending: true
      fieldId: dbt_orders_sum_of_basket_total
  tableCalculations: []
name: Top Partners by Revenue
slug: top-partners-by-revenue-1
spaceSlug: test-space
tableConfig:
  columnOrder:
    - dbt_orders_partner_name
    - dbt_orders_sum_of_basket_total
tableName: dbt_orders
verification: null
version: 1
