chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: true
        type: plain
      series:
        - encode:
            xRef:
              field: dbt_orders_shipping_country
            yRef:
              field: dbt_orders_count_distinct_order_id
          name: Order count
          type: bar
          yAxisIndex: 0
      xAxis:
        - name: Shipping Country
      yAxis:
        - name: Order Count
    layout:
      xField: dbt_orders_shipping_country
      yField:
        - dbt_orders_count_distinct_order_id
  type: cartesian
contentType: chart
dashboardSlug: redwood-ranch-partner-performance-dashboard
description: Shows which countries receive the most shipments from Redwood Ranch orders.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_shipping_country
  exploreName: dbt_orders
  filters:
    dimensions:
      and:
        - id: a5d04146-82df-494d-a9a6-250167fb9b9f
          operator: equals
          target:
            fieldId: dbt_orders_partner_name
          values:
            - Redwood Ranch
      id: 3e2cfc88-f047-4a4c-b85c-489838a02994
    metrics:
      and: []
      id: deb5b73a-4e40-42a6-8d3e-e2811d7bdf9d
  limit: 10
  metricOverrides: {}
  metrics:
    - dbt_orders_count_distinct_order_id
  sorts:
    - descending: true
      fieldId: dbt_orders_count_distinct_order_id
  tableCalculations: []
name: Top Shipping Countries for Redwood Ranch Orders
slug: top-shipping-countries-for-redwood-ranch-orders
spaceSlug: sql-runner-space
tableConfig:
  columnOrder:
    - dbt_orders_shipping_country
    - dbt_orders_count_distinct_order_id
tableName: dbt_orders
verification: null
version: 1
