chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: true
        type: scroll
      series:
        - encode:
            xRef:
              field: dbt_baskets_product_name
            yRef:
              field: dbt_baskets_sum_of_basket_total
          isFilteredOut: false
          name: Revenue
          type: bar
          yAxisIndex: 0
      showAxisTicks: false
      title:
        text: Top 5 products by revenue
      xAxis:
        - name: Product
      yAxis:
        - name: Revenue
    layout:
      stack: false
      xField: dbt_baskets_product_name
      yField:
        - dbt_baskets_sum_of_basket_total
  type: cartesian
contentType: chart
dashboardSlug: "-kpi-dashboard"
description: Ranks products by total revenue (sum of basket totals) and returns the top 5.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_baskets_product_name
  exploreName: dbt_baskets
  filters:
    dimensions:
      and: []
      id: b174a5dd-0e29-43ac-9949-b6e0405cc0a1
    metrics:
      and: []
      id: 1a2bb104-a08b-4718-a570-17cdab0f8ef1
    tableCalculations:
      and: []
      id: 5c86fd2c-8908-4f48-9cb4-c6b3b482398d
  limit: 5
  metricOverrides: {}
  metrics:
    - dbt_baskets_sum_of_basket_total
  sorts:
    - descending: true
      fieldId: dbt_baskets_sum_of_basket_total
  tableCalculations: []
name: Top 5 products by revenue
slug: top-5-products-by-revenue-3
spaceSlug: "-key-company-dashboards"
tableConfig:
  columnOrder:
    - dbt_baskets_product_name
    - dbt_baskets_sum_of_basket_total
tableName: dbt_baskets
verification: null
version: 1
