chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: true
        type: scroll
      series:
        - encode:
            xRef:
              field: dbt_baskets_product_name
            yRef:
              field: dbt_baskets_sum_of_basket_total
          isFilteredOut: false
          name: Revenue
          type: bar
          yAxisIndex: 0
      showAxisTicks: false
      title:
        text: Top 5 products by revenue
      xAxis:
        - name: Product
      yAxis:
        - name: Revenue
    layout:
      stack: false
      xField: dbt_baskets_product_name
      yField:
        - dbt_baskets_sum_of_basket_total
  type: cartesian
contentType: chart
dashboardSlug: "-kpi-dashboard"
description: Ranks products by total Revenue and returns the top 5 products.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_baskets_product_name
  exploreName: dbt_baskets
  filters:
    dimensions:
      and: []
      id: 0a8c2e7e-42df-4d29-aabe-2b5169258ead
    metrics:
      and: []
      id: 30aac9b6-b74b-4c2a-8dde-cd8df08d8edd
    tableCalculations:
      and: []
      id: 76426274-ba88-47fd-85c2-8578d84a89c0
  limit: 5
  metricOverrides: {}
  metrics:
    - dbt_baskets_sum_of_basket_total
  sorts:
    - descending: true
      fieldId: dbt_baskets_sum_of_basket_total
  tableCalculations: []
name: Top 5 products by revenue
slug: top-5-products-by-revenue-4
spaceSlug: "-key-company-dashboards"
tableConfig:
  columnOrder:
    - dbt_baskets_product_name
    - dbt_baskets_sum_of_basket_total
tableName: dbt_baskets
verification: null
version: 1
