chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: true
        type: scroll
      series:
        - encode:
            xRef:
              field: dbt_orders_partner_name
            yRef:
              field: dbt_orders_sum_of_basket_total
          isFilteredOut: false
          name: Sum of basket total
          type: bar
          yAxisIndex: 0
      xAxis:
        - name: Partner
      yAxis:
        - name: Total Revenue
    layout:
      stack: false
      xField: dbt_orders_partner_name
      yField:
        - dbt_orders_sum_of_basket_total
  type: cartesian
contentType: chart
dashboardSlug: sales-kpi-dashboard
description: Bar chart showing the top partners by total revenue.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_partner_name
  exploreName: dbt_orders
  filters:
    dimensions:
      and: []
      id: bba6ec44-c023-4775-a22f-294f6896e74d
    metrics:
      and: []
      id: be050ac5-525f-4ca5-8fbb-375fc4797c49
    tableCalculations:
      and: []
      id: d811c548-758f-4bc4-9490-c2849c4937be
  limit: 10
  metricOverrides: {}
  metrics:
    - dbt_orders_sum_of_basket_total
  sorts:
    - descending: true
      fieldId: dbt_orders_sum_of_basket_total
  tableCalculations: []
name: Top Partners by Revenue
slug: top-partners-by-revenue
spaceSlug: shared/apollo
tableConfig:
  columnOrder:
    - dbt_orders_partner_name
    - dbt_orders_sum_of_basket_total
tableName: dbt_orders
verification: null
version: 1
