chartConfig:
  config:
    eChartsConfig:
      grid:
        containLabel: true
      legend:
        show: false
      series:
        - encode:
            xRef:
              field: dbt_users_created_date_month
            yRef:
              field: dbt_users_count_distinct_of_user_id
          type: bar
          yAxisIndex: 0
      xAxis:
        - name: Month
          type: category
      yAxis:
        - name: Total Users
          type: value
    layout:
      showGridY: true
      xField: dbt_users_created_date_month
      yField:
        - dbt_users_count_distinct_of_user_id
  type: cartesian
contentType: chart
description: Shows total users grouped by the month they were created.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_users_created_date_month
  exploreName: dbt_users
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_users_count_distinct_of_user_id
  sorts:
    - descending: false
      fieldId: dbt_users_created_date_month
  tableCalculations: []
name: Total Users by Created Month
slug: total-users-by-created-month
spaceSlug: "-sales"
tableConfig:
  columnOrder:
    - dbt_users_created_date_month
    - dbt_users_count_distinct_of_user_id
tableName: dbt_users
verification: null
version: 1
