chartConfig:
  config:
    columns: {}
    conditionalFormattings: []
    hideRowNumbers: false
    metricsAsRows: false
    showColumnCalculation: false
    showResultsTotal: false
    showRowCalculation: false
    showSubtotals: false
    showTableNames: true
  type: table
contentType: chart
dashboardSlug: orders-support-team-dashboard
description: Summary of total orders placed in the last 30 days.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions: []
  exploreName: dbt_orders
  filters:
    dimensions:
      and:
        - id: b83927a1-4925-4b7a-8645-0f890b9e7975
          operator: inThePast
          settings:
            completed: true
            unitOfTime: days
          target:
            fieldId: dbt_orders_order_date_day
          values:
            - 30
      id: db5c531f-7af5-46f0-a5b1-3966dcd9b3bb
    metrics:
      and: []
      id: 08d9b466-00ad-404e-a9e6-f6870ad759e2
    tableCalculations:
      and: []
      id: ed3e38ce-7e84-42b9-a517-08a2c4c450e7
  limit: 1
  metricOverrides: {}
  metrics:
    - dbt_orders_count_distinct_order_id
  sorts: []
  tableCalculations: []
name: Total Orders (Last 30 Days)
slug: total-orders-last-30-days
spaceSlug: shared
tableConfig:
  columnOrder:
    - dbt_orders_count_distinct_order_id
tableName: dbt_orders
verification: null
version: 1
