chartConfig:
  config:
    columns: {}
    conditionalFormattings: []
    hideRowNumbers: false
    metricsAsRows: false
    showColumnCalculation: false
    showResultsTotal: false
    showRowCalculation: false
    showSubtotals: false
    showTableNames: true
  type: table
contentType: chart
dashboardSlug: sales-kpi-dashboard
description: >-
  Summary of total revenue, order count, profit, and unique users for the
  selected period.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions: []
  exploreName: dbt_orders
  filters:
    dimensions:
      and: []
      id: 84843874-3624-4c18-82e0-63495c38f135
    metrics:
      and: []
      id: 4f1c2899-d697-4b00-bf43-d8f2d60e3807
    tableCalculations:
      and: []
      id: d929d794-4d77-4aa2-b1fb-b89cba76a1af
  limit: 1000
  metricOverrides: {}
  metrics:
    - dbt_orders_sum_of_basket_total
    - dbt_orders_count_distinct_order_id
    - dbt_orders_sum_of_profit
    - dbt_orders_count_distinct_user_id
  sorts: []
  tableCalculations: []
name: Total Revenue, Orders, Profit, and Unique Users (Summary)
slug: total-revenue-orders-profit-and-unique-users-summary
spaceSlug: shared/apollo
tableConfig:
  columnOrder:
    - dbt_orders_sum_of_basket_total
    - dbt_orders_count_distinct_order_id
    - dbt_orders_sum_of_profit
    - dbt_orders_count_distinct_user_id
tableName: dbt_orders
verification: null
version: 1
