chartConfig:
  config: null
  type: table
contentType: chart
dashboardSlug: redwood-ranch-partner-performance-since-black-friday-2024
description: Total unique orders placed with Redwood Ranch since November 29, 2024.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions: []
  exploreName: dbt_orders
  filters:
    dimensions:
      and:
        - id: d69a8103-9653-4f0b-b29f-a7b6c9a3b339
          operator: equals
          target:
            fieldId: dbt_orders_partner_name
          values:
            - Redwood Ranch
        - id: ebcebb47-60e5-4d01-a6f4-a2e93892f50c
          operator: greaterThanOrEqual
          target:
            fieldId: dbt_orders_order_date_day
          values:
            - "2024-11-29"
      id: cae1788d-9d24-4d00-af00-fe34f672f70b
    metrics:
      and: []
      id: d04e830b-9631-4f76-8ff1-930bd399e5b5
  limit: 1
  metricOverrides: {}
  metrics:
    - dbt_orders_count_distinct_order_id
  sorts:
    - descending: true
      fieldId: dbt_orders_count_distinct_order_id
  tableCalculations: []
name: Total Orders from Redwood Ranch Since Black Friday 2024
slug: total-orders-from-redwood-ranch-since-black-friday-2024
spaceSlug: shared
tableConfig:
  columnOrder:
    - dbt_orders_count_distinct_order_id
tableName: dbt_orders
verification: null
version: 1
