chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: dbt_orders_shipping_country
            yRef:
              field: dbt_orders_sum_of_basket_total
          isFilteredOut: false
          label:
            position: top
            show: true
          type: bar
          yAxisIndex: 0
      showAxisTicks: false
    layout:
      xField: dbt_orders_shipping_country
      yField:
        - dbt_orders_sum_of_basket_total
  type: cartesian
contentType: chart
description: >-
  Compares the sum of basket totals across countries with names starting with A,
  revealing which markets generate the highest order values.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - dbt_orders_shipping_country
  exploreName: dbt_orders
  filters:
    dimensions:
      and:
        - id: 7cd6bcb6-dc2c-42f4-b7c1-14e178627051
          operator: equals
          required: false
          target:
            fieldId: dbt_orders_shipping_country
          values:
            - AD
            - AE
            - AF
            - AG
            - AI
            - AL
            - AM
            - AO
            - AQ
            - AR
            - AS
            - AW
            - AT
            - AU
            - AX
            - AZ
            - BA
            - BB
            - BG
            - BH
            - BI
            - BJ
            - BL
            - BM
            - BN
      id: 3e8bf360-dde0-4a7e-9592-85df3cdf6a9d
  limit: 500
  metricOverrides:
    dbt_orders_sum_of_basket_total:
      formatOptions:
        compact: thousands
        round: 0
        separator: default
        type: number
  metrics:
    - dbt_orders_sum_of_basket_total
  sorts:
    - descending: false
      fieldId: dbt_orders_shipping_country
  tableCalculations: []
name: Total basket value by shipping country (A countries)
pivotConfig:
  columns:
    - dbt_orders_partner_logo
slug: total-basket-value-by-shipping-country-a-countries
spaceSlug: shared
tableConfig:
  columnOrder:
    - dbt_orders_shipping_country
    - dbt_orders_sum_of_basket_total
tableName: dbt_orders
verification: null
version: 1
