chartConfig:
  config:
    columns: {}
    conditionalFormattings: []
    hideRowNumbers: false
    metricsAsRows: false
    showColumnCalculation: false
    showResultsTotal: false
    showRowCalculation: false
    showSubtotals: false
    showTableNames: true
  type: table
contentType: chart
dashboardSlug: partner-performance-dashboard
description: Summary of total orders and total basket revenue for all partners.
metricQuery:
  additionalMetrics:
    - baseDimensionName: dbt_orders_count_distinct_order_id
      description: Count of distinct order IDs across all partners.
      label: Total Orders
      name: total_orders
      sql: "`dbt_orders_count_distinct_order_id`"
      table: monthly_partner_info
      type: sum
      uuid: 59d79b21-8ba4-4a4c-b1b4-788c8de8318e
    - baseDimensionName: dbt_orders_sum_basket_total
      description: Sum of basket totals across all orders for all partners.
      label: Total Revenue
      name: total_revenue
      sql: "`dbt_orders_sum_of_basket_total`"
      table: monthly_partner_info
      type: sum
      uuid: 20b9641c-c655-4c19-b0c1-ff403f81c929
  customDimensions: []
  dimensions: []
  exploreName: monthly_partner_info
  filters:
    dimensions:
      and: []
      id: 2869d9ef-23c1-49fd-80a4-13c142903953
    metrics:
      and: []
      id: 70722d14-8c2e-4947-a80f-ec80f99c14c2
    tableCalculations:
      and: []
      id: b5dbdc7e-13ba-4871-9eb6-6cc038587151
  limit: 1000
  metricOverrides: {}
  metrics:
    - monthly_partner_info_total_orders
    - monthly_partner_info_total_revenue
  sorts: []
  tableCalculations: []
name: Total Orders and Revenue (All Time)
slug: total-orders-and-revenue-all-time
spaceSlug: shared/apollo
tableConfig:
  columnOrder:
    - monthly_partner_info_total_orders
    - monthly_partner_info_total_revenue
tableName: monthly_partner_info
verification: null
version: 1
