chartKind: vertical_bar
config:
  display: {}
  fieldConfig:
    groupBy: []
    sortBy:
      - direction: ASC
        reference: order_id
    x:
      reference: order_id
      type: category
    "y":
      - aggregation: sum
        reference: basket_total
  metadata:
    version: 1
  type: vertical_bar
contentType: sql_chart
description: ""
limit: 500
name: uh chart
slug: uh-chart
spaceSlug: shared/shared-nested
sql: "SELECT * FROM `lightdash-healthcare-demo`.`dbt_jake`.`baskets` "
version: 1
