chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: dbt_orders_count_distinct_order_id_u_s_orders
            yRef:
              field: dbt_orders_count_distinct_order_id_non_u_s
          isFilteredOut: false
          type: bar
          yAxisIndex: 0
    layout:
      xField: dbt_orders_count_distinct_order_id_u_s_orders
      yField:
        - dbt_orders_count_distinct_order_id_non_u_s
  type: cartesian
contentType: chart
description: null
metricQuery:
  additionalMetrics:
    - baseDimensionName: order_id
      description: >-
        Count of US Orders on the table Orders with filters
        dbt_orders.shipping_country
      filters:
        - id: 3e80c603-fb8b-4e53-a8b8-6d32a655b6a6
          operator: equals
          target:
            fieldRef: dbt_orders.shipping_country
          values:
            - US
      formatOptions:
        separator: default
        type: default
      label: US Orders
      name: order_id_u_s_orders
      sql: ${TABLE}.order_id
      table: dbt_orders
      type: count
      uuid: 387224ae-6d4e-4f25-8c27-68416aca596c
    - baseDimensionName: order_id
      description: >-
        Count of Order id on the table Orders with filters
        dbt_orders.shipping_country
      filters:
        - id: f3ab6df1-cc4f-4d6e-87b0-b6b0599b65d8
          operator: notEquals
          target:
            fieldRef: dbt_orders.shipping_country
          values:
            - US
      formatOptions:
        separator: default
        type: default
      label: Non-US
      name: order_id_non_u_s
      sql: ${TABLE}.order_id
      table: dbt_orders
      type: count
      uuid: e64e8292-e6b4-4c40-a772-53ad020dcbdf
  customDimensions: []
  dimensions:
    - dbt_orders_partner_name
  exploreName: dbt_orders
  filters:
    dimensions:
      and:
        - id: 07d3ec88-ce02-4010-a253-4e8f54c1ff66
          operator: equals
          target:
            fieldId: dbt_orders_count_distinct_order_id
          values: []
      id: ad3a8d42-2931-427e-9329-c7926b4645a8
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_count_distinct_order_id_u_s_orders
    - dbt_orders_count_distinct_order_id_non_u_s
  sorts:
    - descending: false
      fieldId: dbt_orders_partner_name
  tableCalculations: []
name: US v Non US Orders
slug: us-v-non-us-orders
spaceSlug: shared
tableConfig:
  columnOrder:
    - dbt_orders_partner_name
    - dbt_orders_count_distinct_order_id_u_s_orders
    - dbt_orders_count_distinct_order_id_non_u_s
tableName: dbt_orders
verification: null
version: 1
