chartConfig:
  config:
    columns:
      dbt_orders_average_of_basket_total:
        name: Average order value
    showColumnCalculation: false
    showTableNames: false
  type: table
contentType: chart
description: null
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - dbt_orders_referrer
  exploreName: dbt_orders
  filters: {}
  limit: 500
  metrics:
    - dbt_orders_average_of_basket_total
  sorts:
    - descending: true
      fieldId: dbt_orders_average_of_basket_total
  tableCalculations: []
name: What is the average order value for each referrer?
slug: what-is-the-average-order-value-for-each-referrer-
spaceSlug: katie-private-space
tableConfig:
  columnOrder:
    - dbt_orders_referrer
    - dbt_orders_average_of_basket_total
tableName: dbt_orders
verification: null
version: 1
