chartConfig:
  config:
    comparisonFormat: raw
    comparisonLabel: MoM
    conditionalFormattings:
      - color: "#ff7a6b"
        darkColor: "#ffb898"
        rules:
          - id: 85420c3b-beef-4a2d-b323-b5f962d41224
            operator: lessThan
            values:
              - 200000
        target: null
      - color: "#ffc658"
        darkColor: "#ffeabd"
        rules:
          - id: 574df166-2f56-45ef-a78f-76a9257072ca
            operator: inBetween
            values:
              - 200000
              - 250000
        target: null
      - color: "#7cde96"
        darkColor: "#b8f5c8"
        rules:
          - id: ab1744e7-e611-4f1a-9824-60b1c185c3d6
            operator: greaterThanOrEqual
            values:
              - 250000
        target: null
    flipColors: false
    label: Total Revenue
    selectedField: dbt_orders_sum_of_basket_total
    showBigNumberLabel: true
    showComparison: true
    showTableNamesInLabel: true
    style: thousands
  type: big_number
contentType: chart
description: "The total revenue we get every month from all customers "
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_order_date_month
    - dbt_orders_partner_commission
  exploreName: dbt_orders
  filters:
    dimensions:
      and:
        - id: fecaec2a-1397-401b-8d36-ad6de29b9b31
          operator: equals
          required: false
          target:
            fieldId: dbt_orders_browser
          values: []
      id: 7d05215d-1fd7-4bda-8694-d9d3cee4da83
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_sum_of_basket_total
    - dbt_orders_sum_of_profit
  sorts:
    - descending: true
      fieldId: dbt_orders_sum_of_basket_total
  tableCalculations: []
name: What is our total revenue this month?
slug: what-is-our-total-revenue-
spaceSlug: "-sales"
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_partner_commission
    - dbt_orders_sum_of_basket_total
    - dbt_orders_sum_of_profit
tableName: dbt_orders
verification: null
version: 1
