chartConfig:
  config:
    eChartsConfig:
      grid:
        bottom: 5px
        containLabel: true
        left: 5px
        right: 5px
        top: 35px
      series:
        - areaStyle: {}
          encode:
            xRef:
              field: dbt_support_requests_request_date_week
            yRef:
              field: dbt_support_requests_count_distinct_request_id
              pivotValues:
                - field: dbt_support_requests_reason
                  value: Delivery issue
          isFilteredOut: false
          label:
            show: false
          showSymbol: false
          smooth: false
          stack: dbt_support_requests_count_distinct_request_id
          stackLabel:
            show: true
          type: line
          yAxisIndex: 0
        - areaStyle: {}
          encode:
            xRef:
              field: dbt_support_requests_request_date_week
            yRef:
              field: dbt_support_requests_count_distinct_request_id
              pivotValues:
                - field: dbt_support_requests_reason
                  value: Payment issue
          isFilteredOut: false
          label:
            show: false
          showSymbol: false
          smooth: false
          stack: dbt_support_requests_count_distinct_request_id
          stackLabel:
            show: true
          type: line
          yAxisIndex: 0
        - areaStyle: {}
          encode:
            xRef:
              field: dbt_support_requests_request_date_week
            yRef:
              field: dbt_support_requests_count_distinct_request_id
              pivotValues:
                - field: dbt_support_requests_reason
                  value: Product related query
          isFilteredOut: false
          label:
            show: false
          showSymbol: false
          smooth: false
          stack: dbt_support_requests_count_distinct_request_id
          stackLabel:
            show: true
          type: line
          yAxisIndex: 0
        - areaStyle: {}
          encode:
            xRef:
              field: dbt_support_requests_request_date_week
            yRef:
              field: dbt_support_requests_count_distinct_request_id
              pivotValues:
                - field: dbt_support_requests_reason
                  value: Wrong item received
          isFilteredOut: false
          label:
            show: false
          showSymbol: false
          smooth: false
          stack: dbt_support_requests_count_distinct_request_id
          stackLabel:
            show: true
          type: line
          yAxisIndex: 0
      tooltip: ""
      xAxis:
        - name: " "
          rotate: 30
      yAxis:
        - name: " "
        - {}
    layout:
      flipAxes: false
      showGridY: false
      showYAxis: true
      stack: stack100
      xField: dbt_support_requests_request_date_week
      yField:
        - dbt_support_requests_count_distinct_request_id
  type: cartesian
contentType: chart
description: null
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_support_requests_reason
    - dbt_support_requests_request_date_week
  exploreName: dbt_support_requests
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_support_requests_count_distinct_request_id
  sorts:
    - descending: true
      fieldId: dbt_support_requests_request_date_week
    - descending: false
      fieldId: dbt_support_requests_reason
  tableCalculations: []
name: What support request reasons are the most common by percentage?
pivotConfig:
  columns:
    - dbt_support_requests_reason
slug: what-support-request-reasons-are-the-most-common-
spaceSlug: shared
tableConfig:
  columnOrder:
    - dbt_support_requests_reason
    - dbt_support_requests_request_date_week
    - dbt_support_requests_count_distinct_request_id
tableName: dbt_support_requests
verification: null
version: 1
