chartConfig:
  config:
    comparisonFormat: raw
    conditionalFormattings: []
    flipColors: false
    selectedField: test_val
    showBigNumberLabel: true
    showComparison: false
    showTableNamesInLabel: false
  type: big_number
contentType: chart
dashboardSlug: lightdash-dashboard-1
description: Displays the Test Val metric from the dbt_users data source.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions: []
  exploreName: dbt_users
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_max_order_profit
  sorts:
    - descending: true
      fieldId: dbt_orders_max_order_profit
  tableCalculations:
    - displayName: Test Val
      format:
        separator: default
        type: default
      name: test_val
      sql: ${dbt_orders.max_order_profit}*1.31
      type: number
name: What is the Test Val?
slug: what-is-the-test-val
spaceSlug: shared
tableConfig:
  columnOrder:
    - dbt_orders_max_order_profit
    - test_val
tableName: dbt_users
verification: null
version: 1
