chartConfig:
  config:
    columns:
      dbt_orders_currency:
        width: 50
      dbt_orders_email:
        width: 201.203125
      dbt_orders_partner_name:
        width: 96.078125
    conditionalFormattings: []
    hideRowNumbers: false
    metricsAsRows: false
    showColumnCalculation: false
    showResultsTotal: false
    showRowCalculation: false
    showSubtotals: false
    showTableNames: false
  type: table
contentType: chart
dashboardSlug: dashboard-with-tabs-test-saving-to
description: >-
  View a detailed table of customer emails, payment currencies, and fulfilling
  partners across all orders to understand customer distribution and partner
  involvement.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_basket_total
    - dbt_orders_browser
    - dbt_orders_currency
    - dbt_orders_email
    - dbt_orders_is_sunday
    - dbt_orders_order_date_day
    - dbt_orders_partner_name
    - dbt_orders_shipping_country
    - dbt_orders_shipping_city
    - dbt_orders_profit
    - dbt_orders_referrer
  exploreName: dbt_orders
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_average_of_basket_total
    - dbt_orders_distinct_partners
    - dbt_orders_avg_profit
    - dbt_orders_max_order_profit
    - dbt_orders_sum_of_profit
    - dbt_orders_sum_of_basket_total
    - dbt_orders_median_profit
    - dbt_orders_count_distinct_order_id
    - dbt_orders_count_distinct_user_id
  sorts:
    - descending: false
      fieldId: dbt_orders_basket_total
  tableCalculations: []
name: What are the email addresses, currencies, and partners for all orders?
slug: what-are-the-email-addresses-currencies-and-partners-for-all-orders
spaceSlug: "-sales"
tableConfig:
  columnOrder:
    - dbt_orders_basket_total
    - dbt_orders_browser
    - dbt_orders_currency
    - dbt_orders_email
    - dbt_orders_is_sunday
    - dbt_orders_order_date_day
    - dbt_orders_partner_name
    - dbt_orders_shipping_country
    - dbt_orders_shipping_city
    - dbt_orders_profit
    - dbt_orders_referrer
    - dbt_orders_average_of_basket_total
    - dbt_orders_distinct_partners
    - dbt_orders_avg_profit
    - dbt_orders_max_order_profit
    - dbt_orders_sum_of_profit
    - dbt_orders_sum_of_basket_total
    - dbt_orders_median_profit
    - dbt_orders_count_distinct_order_id
    - dbt_orders_count_distinct_user_id
tableName: dbt_orders
verification: null
version: 1
