chartConfig:
  config:
    eChartsConfig:
      grid:
        bottom: 15px
        containLabel: true
        left: 5px
        right: 5px
        top: 5px
      series:
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: average_orders_per_user
          isFilteredOut: false
          label:
            position: top
            show: true
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_count_distinct_order_id
          isFilteredOut: true
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_count_distinct_user_id
          isFilteredOut: true
          type: bar
          yAxisIndex: 0
      showAxisTicks: false
      xAxis:
        - name: " "
      yAxis:
        - name: ""
        - name: ""
    layout:
      flipAxes: false
      showGridY: false
      showYAxis: false
      xField: dbt_orders_order_date_month
      yField:
        - average_orders_per_user
        - dbt_orders_count_distinct_order_id
        - dbt_orders_count_distinct_user_id
  type: cartesian
contentType: chart
description: Bar chart showing average orders per month per user
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_order_date_month
  exploreName: dbt_orders
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_count_distinct_user_id
    - dbt_orders_count_distinct_order_id
  sorts:
    - descending: true
      fieldId: dbt_orders_order_date_month
  tableCalculations:
    - displayName: average orders per user
      name: average_orders_per_user
      sql: ROUND(${dbt_orders.order_id}/${dbt_orders.count_distinct_user_id}, 2)
name: Average order count per user per month
slug: what-s-the-average-number-of-weekly-orders-per-user-
spaceSlug: shared
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_count_distinct_user_id
    - dbt_orders_count_distinct_order_id
    - average_orders_per_user
tableName: dbt_orders
verification: null
version: 1
