chartConfig:
  config:
    comparisonFormat: percentage
    comparisonLabel: MoM
    flipColors: false
    label: Total profit
    selectedField: dbt_orders_sum_of_profit
    showBigNumberLabel: true
    showComparison: true
    style: thousands
  type: big_number
contentType: chart
description: >-
  Profit is defined by using a very complex calculation that will take a while
  to explain...
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_order_date_month
  exploreName: dbt_orders
  filters:
    dimensions:
      and:
        - id: ce668ead-3b3e-4c6b-bc22-89e9a9f9c45d
          operator: greaterThan
          target:
            fieldId: dbt_orders_basket_total
          values:
            - 1
      id: 1c575be5-4220-4b4e-9cd2-795930067e8d
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_sum_of_profit
    - dbt_orders_sum_of_basket_total
  sorts:
    - descending: true
      fieldId: dbt_orders_sum_of_profit
  tableCalculations: []
name: What is our total profit?
slug: what-is-our-total-profit-
spaceSlug: "-sales"
tableConfig:
  columnOrder:
    - dbt_orders_order_date_month
    - dbt_orders_sum_of_profit
    - dbt_orders_sum_of_basket_total
tableName: dbt_orders
verification: null
version: 1
