chartConfig:
  config:
    eChartsConfig:
      legend:
        left: 25px
        orient: vertical
        show: false
        type: plain
      series:
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_basket_total
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Plant Paradise
          isFilteredOut: false
          stack: dbt_orders_sum_of_basket_total
          stackLabel:
            show: true
          type: bar
          yAxisIndex: 0
        - color: "#a78bfa"
          encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_basket_total
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Garden of Sweden
          isFilteredOut: false
          stack: dbt_orders_sum_of_basket_total
          stackLabel:
            show: true
          type: bar
          yAxisIndex: 0
        - color: "#8b8cf6"
          encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_basket_total
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Redwood Ranch
          isFilteredOut: false
          stack: dbt_orders_sum_of_basket_total
          stackLabel:
            show: true
          type: bar
          yAxisIndex: 0
        - color: "#ff7eb9"
          encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_basket_total
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Trowels R Us
          isFilteredOut: false
          stack: dbt_orders_sum_of_basket_total
          stackLabel:
            show: true
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_basket_total
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Peat, Fruits and Leaves
          isFilteredOut: false
          stack: dbt_orders_sum_of_basket_total
          stackLabel:
            show: true
          type: bar
          yAxisIndex: 0
        - color: "#5dd9d2"
          encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_basket_total
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Sprout Society
          isFilteredOut: false
          stack: dbt_orders_sum_of_basket_total
          stackLabel:
            show: true
          type: bar
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_basket_total
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Roots & Shoots
          isFilteredOut: false
          stack: dbt_orders_sum_of_basket_total
          stackLabel:
            show: true
          type: bar
          yAxisIndex: 0
        - color: "#ffb898"
          encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_basket_total
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Happy Harvesters
          isFilteredOut: false
          stack: dbt_orders_sum_of_basket_total
          stackLabel:
            show: true
          type: bar
          yAxisIndex: 0
        - color: "#ffc658"
          encode:
            xRef:
              field: dbt_orders_order_date_month
            yRef:
              field: dbt_orders_sum_of_basket_total
              pivotValues:
                - field: dbt_orders_partner_name
                  value: Potted Paradise
          isFilteredOut: false
          stack: dbt_orders_sum_of_basket_total
          stackLabel:
            show: true
          type: bar
          yAxisIndex: 0
      showAxisTicks: false
      tooltip: ""
      xAxis:
        - name: Month
    layout:
      flipAxes: false
      showGridX: false
      showGridY: true
      showXAxis: true
      showYAxis: true
      xField: dbt_orders_order_date_month
      yField:
        - dbt_orders_sum_of_basket_total
    metadata:
      dbt_orders_sum_of_basket_total.Garden of Sweden:
        color: "#a78bfa"
      dbt_orders_sum_of_basket_total.Happy Harvesters:
        color: "#ffb898"
      dbt_orders_sum_of_basket_total.Potted Paradise:
        color: "#ffc658"
      dbt_orders_sum_of_basket_total.Redwood Ranch:
        color: "#8b8cf6"
      dbt_orders_sum_of_basket_total.Sprout Society:
        color: "#5dd9d2"
      dbt_orders_sum_of_basket_total.Trowels R Us:
        color: "#ff7eb9"
  type: cartesian
contentType: chart
description: null
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_partner_name
    - dbt_orders_order_date_month
  exploreName: dbt_orders
  filters: {}
  limit: 500
  metricOverrides:
    dbt_orders_sum_of_basket_total:
      formatOptions:
        currency: USD
        round: 0
        separator: default
        type: currency
  metrics:
    - dbt_orders_count_distinct_order_id
    - dbt_orders_sum_of_basket_total
    - dbt_orders_average_of_basket_total
  sorts:
    - descending: false
      fieldId: dbt_orders_order_date_month
  tableCalculations: []
name: What are the sales stats per partner, per month?
pivotConfig:
  columns:
    - dbt_orders_partner_name
slug: what-are-the-sales-stats-per-partner-per-month-
spaceSlug: "-sales"
tableConfig:
  columnOrder:
    - dbt_orders_partner_name
    - dbt_orders_order_date_month
    - dbt_orders_count_distinct_order_id
    - dbt_orders_sum_of_basket_total
    - dbt_orders_average_of_basket_total
tableName: dbt_orders
verification: null
version: 1
