chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: dbt_orders_partner_name
            yRef:
              field: dbt_orders_average_of_basket_total
          isFilteredOut: false
          type: bar
          yAxisIndex: 0
      showAxisTicks: false
    layout:
      xField: dbt_orders_partner_name
      yField:
        - dbt_orders_average_of_basket_total
  type: cartesian
contentType: chart
dashboardSlug: pre-aggregates-sneak-peek
description: >-
  Compares average customer spending per order across different partners to
  identify which partners drive higher transaction values.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_partner_name
  exploreName: dbt_orders
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_average_of_basket_total
  sorts:
    - descending: true
      fieldId: dbt_orders_average_of_basket_total
  tableCalculations: []
name: What is the average order value by partner?
slug: what-is-the-average-order-value-by-partner
spaceSlug: shared/dashcachedemo
tableConfig:
  columnOrder:
    - dbt_orders_partner_name
    - dbt_orders_average_of_basket_total
tableName: dbt_orders
verification: null
version: 1
