chartConfig:
  config:
    columns: {}
    conditionalFormattings: []
    hideRowNumbers: false
    metricsAsRows: false
    showColumnCalculation: false
    showResultsTotal: false
    showRowCalculation: false
    showSubtotals: false
    showTableNames: false
  type: table
contentType: chart
dashboardSlug: hamzahs-new-fantastic-dashboard
description: >-
  The chart reveals the unique order counts fulfilled by each partner,
  highlighting their performance in order fulfillment.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_partner_name
  exploreName: dbt_orders
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_orders_count_distinct_order_id
  sorts:
    - descending: true
      fieldId: dbt_orders_count_distinct_order_id
  tableCalculations: []
name: Which partners have the highest order counts?
slug: which-partners-have-the-highest-order-counts
spaceSlug: shared
tableConfig:
  columnOrder:
    - dbt_orders_partner_name
    - dbt_orders_count_distinct_order_id
tableName: dbt_orders
verification: null
version: 1
