chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: dbt_orders_order_date_day
            yRef:
              field: dbt_orders_sum_of_basket_total
          isFilteredOut: false
          smooth: true
          type: line
          yAxisIndex: 0
        - encode:
            xRef:
              field: dbt_orders_order_date_day
            yRef:
              field: dbt_orders_avg_profit
          isFilteredOut: false
          smooth: true
          type: line
          yAxisIndex: 0
      showAxisTicks: false
    layout:
      flipAxes: false
      stack: none
      xField: dbt_orders_order_date_day
      yField:
        - dbt_orders_sum_of_basket_total
        - dbt_orders_avg_profit
  type: cartesian
contentType: chart
description: >-
  Tracks daily Revenue and Profit trends to identify patterns in sales
  performance and profitability across all order dates.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_orders_order_date_day
  exploreName: dbt_orders
  filters: {}
  limit: 10000
  metricOverrides: {}
  metrics:
    - dbt_orders_sum_of_basket_total
    - dbt_orders_avg_profit
  sorts:
    - descending: true
      fieldId: dbt_orders_sum_of_basket_total
  tableCalculations: []
name: "[Without DashCache] How do Revenue and Profit trend over time?"
pivotConfig:
  columns:
    - dbt_orders_shipping_country
    - dbt_orders_browser
slug: without-dashcache-how-do-revenue-and-profit-trend-over-time
spaceSlug: shared/dashcachedemo
tableConfig:
  columnOrder:
    - dbt_orders_order_date_day
    - dbt_orders_sum_of_basket_total
    - dbt_orders_avg_profit
tableName: dbt_orders
verification: null
version: 1
