chartConfig:
  config:
    columns:
      dbt_baskets_item_profit_margin_tier:
        name: Tier
      dbt_baskets_partner_name:
        name: ""
      dbt_baskets_product_name:
        name: ""
      dbt_baskets_sum_of_item_profit:
        name: ""
    conditionalFormattings:
      - color: "#D4E8D4"
        rules:
          - id: rule-1
            operator: greaterThan
            values:
              - 1000
        target:
          fieldId: dbt_baskets_sum_of_item_profit
      - color: "#B8D4B8"
        rules:
          - id: rule-2
            operator: greaterThan
            values:
              - 5000
        target:
          fieldId: dbt_baskets_sum_of_item_profit
      - color: "#9CC09C"
        rules:
          - id: rule-3
            operator: greaterThan
            values:
              - 10000
        target:
          fieldId: dbt_baskets_sum_of_item_profit
      - color: "#80AC80"
        rules:
          - id: rule-4
            operator: greaterThan
            values:
              - 15000
        target:
          fieldId: dbt_baskets_sum_of_item_profit
      - color: "#649864"
        rules:
          - id: rule-5
            operator: greaterThan
            values:
              - 20000
        target:
          fieldId: dbt_baskets_sum_of_item_profit
    hideRowNumbers: false
    metricsAsRows: false
    showColumnCalculation: false
    showResultsTotal: false
    showRowCalculation: false
    showSubtotals: false
    showTableNames: false
  type: table
contentType: chart
description: ""
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensionOverrides: {}
  dimensions:
    - dbt_baskets_product_name
    - dbt_baskets_partner_name
    - dbt_baskets_item_profit_margin_tier
    - dbt_baskets_currency
  exploreName: dbt_baskets
  filters: {}
  limit: 500
  metricOverrides: {}
  metrics:
    - dbt_baskets_sum_of_item_profit
  sorts:
    - descending: true
      fieldId: dbt_baskets_sum_of_item_profit
  tableCalculations: []
name: "[Without dashcache] What are the most profitable products?"
slug: without-dashcache-what-are-the-most-profitable-products-1772186715150
spaceSlug: "-sales"
tableConfig:
  columnOrder:
    - dbt_baskets_product_name
    - dbt_baskets_partner_name
    - dbt_baskets_item_profit_margin_tier
    - dbt_baskets_currency
    - dbt_baskets_sum_of_item_profit
tableName: dbt_baskets
verification: null
version: 1
