
name: 'lightdash_demo_thyme'
version: '1.7.6'

profile: 'lightdash_demo_thyme'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  lightdash_demo_thyme:
    +materialized: table

seeds:
  lightdash_demo_thyme:
    +enabled: true
