chartConfig:
  config:
    eChartsConfig:
      series:
        - encode:
            xRef:
              field: dbt_orders_partner_name
            yRef:
              field: dbt_orders_sum_of_basket_total
          type: bar
    layout:
      flipAxes: true
      xField: dbt_orders_partner_name
      yField:
        - dbt_orders_sum_of_basket_total
  type: cartesian
contentType: chart
dashboardSlug: executive-sales-dashboard
description: Top partners by revenue over the trailing 12 completed months.
metricQuery:
  additionalMetrics: []
  customDimensions: []
  dimensions:
    - dbt_orders_partner_name
  exploreName: dbt_orders
  filters:
    dimensions:
      and:
        - id: a14ba297-20eb-4ca8-9fbf-90efe43d52cd
          operator: inThePast
          settings:
            completed: true
            unitOfTime: months
          target:
            fieldId: dbt_orders_order_date_month
            tableName: dbt_orders
          values:
            - 12
      id: d7ebcaa7-16b4-4b60-aac8-36ca13283482
  limit: 15
  metricOverrides: {}
  metrics:
    - dbt_orders_sum_of_basket_total
  sorts:
    - descending: true
      fieldId: dbt_orders_sum_of_basket_total
  tableCalculations: []
  timezone: project_timezone
name: Revenue by Partner
slug: exec-revenue-by-partner
spaceSlug: "-sales"
tableConfig:
  columnOrder:
    - dbt_orders_partner_name
    - dbt_orders_sum_of_basket_total
tableName: dbt_orders
verification: null
version: 1
